//! Canon set synergies: Blood (0-29), Wisdom (30-59), Food (60-89).
//! Members are canon Gu names (resolved to table indices at runtime).

use super::{Fx, SynergyDef};

pub const SY_A: &[SynergyDef] = &[
    // ---- Blood Path (7) ----
    syn!(0, 7, "Sanguine Drain", "Hits bleed; siphon drinks back HP.", &["Blood Dripping Gu", "Blood Siphon Gu"], Fx { lifesteal: 0.05, ..Fx::NONE }),
    syn!(1, 7, "Blood Shielding", "Bloodied ground feeds your ward.", &["Blood Shield Gu", "Blood Stain Gu"], Fx { guard: 0.90, shieldkill: 3.0, ..Fx::NONE }),
    syn!(2, 7, "Blood Moon Burst", "Crescents detonate on bleeding foes.", &["Blood Moon Gu", "Blood Blade Gu"], Fx { power: 1.15, ..Fx::NONE }),
    syn!(3, 7, "Ancestral Offering", "Elites widen the aperture forever.", &["Blood Skull Gu", "Blood Asset Gu"], Fx { essence_max: 20.0, power: 1.08, ..Fx::NONE }),
    syn!(4, 7, "Vein Torrent", "A wave herds the room into one knot.", &["Blood Torrent Gu", "Blood Wave Gu"], Fx { power: 1.10, speed: 1.05, ..Fx::NONE }),
    syn!(5, 7, "Vampiric Arrow", "Trail bleeds snap back through the pack.", &["Blood Dripping Gu", "Blood Arrow Gu", "Blood Siphon Gu"], Fx { lifesteal: 0.06, power: 1.10, ..Fx::NONE }),
    syn!(6, 7, "Sanguine Fortress", "Heavy hits freeze blood into a shell.", &["Blood Shield Gu", "Blood Armor Gu", "Blood Stasis Gu"], Fx { guard: 0.85, shieldkill: 4.0, ..Fx::NONE }),
    syn!(7, 7, "Crimson Clone", "A blood phantom spears beside you.", &["Blood Clone Gu", "Blood Spear Gu", "Blood Qi Gu"], Fx { power: 1.20, speed: 1.05, ..Fx::NONE }),
    syn!(8, 7, "Blood Boil Burst", "The slain erupt in healing spray.", &["Blood Boil Gu", "Blood Siphon Gu", "Blood Wave Gu"], Fx { lifesteal: 0.07, power: 1.12, ..Fx::NONE }),
    syn!(9, 7, "Lineage Aegis", "Stored essence hardens into a barrier.", &["Blood Lineage Gu", "Blood Asset Gu", "Blood Shield Gu"], Fx { guard: 0.88, essence_max: 15.0, ..Fx::NONE }),
    syn!(10, 7, "Sanguine Loop", "Bleed, convert, siphon, refresh.", &["Blood Dripping Gu", "Blood Arrow Gu", "Blood Siphon Gu", "Blood Shield Gu"], Fx { lifesteal: 0.09, guard: 0.90, ..Fx::NONE }),
    syn!(11, 7, "Hemolytic Cleave", "Cleansing sweeps reset the arts.", &["Blood Blade Gu", "Blood Spear Gu", "Blood Purification Gu", "Blood Siphon Gu"], Fx { power: 1.22, essence_regen: 2.0, ..Fx::NONE }),
    syn!(12, 7, "Shadow Blood March", "Air-dashes leave thrusting phantasms.", &["Blood Shadow Gu", "Blood Clone Gu", "Blood Wing Gu", "Blood Qi Gu"], Fx { speed: 1.15, power: 1.15, ..Fx::NONE }),
    syn!(13, 7, "Crimson Contract", "Burn HP now for slaughter speed.", &["Blood Contract Gu", "Blood Skull Gu", "Blood Asset Gu", "Blood Essence Gu"], Fx { power: 1.35, speed: 1.12, ..Fx::NONE }),
    syn!(14, 7, "Deity's Domain", "An ocean that drags foes to center.", &["Blood Deity Gu", "Blood Sea Gu", "Blood Wave Gu", "Blood Flow Gu"], Fx { power: 1.20, magnet: 4.0, ..Fx::NONE }),
    syn!(15, 7, "Bloodline Rebirth", "Death refused; return at full HP.", &["Blood Deity Gu", "Blood Skull Gu", "Blood Asset Gu", "Blood Essence Gu", "Blood Lineage Gu"], Fx { revive: true, max_hp: 1.20, ..Fx::NONE }),
    syn!(16, 7, "Sanguine Annihilation", "The screen boils; you drink it all.", &["Blood Torrent Gu", "Blood Spear Gu", "Blood Boil Gu", "Blood Siphon Gu", "Blood Sea Gu"], Fx { power: 1.35, lifesteal: 0.10, ..Fx::NONE }),
    syn!(17, 7, "Blood Stalker", "Dark-coated blades always find backs.", &["Blood Shadow Gu", "Blood Blade Gu"], Fx { crit: 0.10, speed: 1.05, ..Fx::NONE }),
    syn!(18, 7, "Vessel Overcharge", "Faster hands, slow HP tithe.", &["Blood Qi Gu", "Blood Essence Gu"], Fx { power: 1.12, regen: 0.5, ..Fx::NONE }),
    syn!(19, 7, "Purifying Tide", "Cleanse everything; run the red road.", &["Blood Purification Gu", "Blood Flow Gu"], Fx { speed: 1.10, guard: 0.95, ..Fx::NONE }),
    syn!(20, 7, "Blood Siphon Trap", "Puddles root and sip the stepping.", &["Blood Stain Gu", "Blood Siphon Gu", "Blood Stasis Gu"], Fx { lifesteal: 0.05, thorns: 0.15, ..Fx::NONE }),
    syn!(21, 7, "Crimson Volley", "Five arrows that shove the room.", &["Blood Arrow Gu", "Blood Wave Gu", "Blood Qi Gu"], Fx { arrows: 2, power: 1.08, ..Fx::NONE }),
    syn!(22, 7, "Sanguine Armor Burst", "Shattered armor spikes the swarm.", &["Blood Armor Gu", "Blood Boil Gu", "Blood Dripping Gu"], Fx { thorns: 0.35, guard: 0.92, ..Fx::NONE }),
    syn!(23, 7, "Curse of the Flesh", "Half your pain belongs to the marked.", &["Blood Contract Gu", "Blood Dripping Gu", "Blood Shadow Gu"], Fx { power: 1.15, lifesteal: 0.04, ..Fx::NONE }),
    syn!(24, 7, "Sanguine Feast", "The fed body keeps growing.", &["Blood Sea Gu", "Blood Siphon Gu", "Blood Asset Gu", "Blood Essence Gu"], Fx { max_hp: 1.15, lifesteal: 0.06, ..Fx::NONE }),
    syn!(25, 7, "Phantoms of the Fallen", "Wall-walking clones seed blind trails.", &["Blood Clone Gu", "Blood Shadow Gu", "Blood Soul Gu", "Blood Spear Gu"], Fx { power: 1.20, dodge: 0.05, ..Fx::NONE }),
    syn!(26, 7, "Heartbeat Pulse", "A pulse that finds the hidden.", &["Blood Flow Gu", "Blood Qi Gu"], Fx { magnet: 3.0, speed: 1.05, ..Fx::NONE }),
    syn!(27, 7, "Vampiric Burst", "All bleeds detonate at once.", &["Blood Dripping Gu", "Blood Siphon Gu", "Blood Essence Gu"], Fx { power: 1.22, lifesteal: 0.05, ..Fx::NONE }),
    syn!(28, 7, "Blood Bastion", "Stillness becomes a mirror wall.", &["Blood Shield Gu", "Blood Stasis Gu", "Blood Armor Gu", "Blood Lineage Gu"], Fx { guard: 0.82, thorns: 0.30, ..Fx::NONE }),
    syn!(29, 7, "Absolute Sanguine Domain", "Their healing wounds them; arts cost nothing.", &["Blood Deity Gu", "Blood Torrent Gu", "Blood Sea Gu", "Blood Purification Gu", "Blood Essence Gu"], Fx { power: 1.30, essence_regen: 5.0, lifesteal: 0.08, ..Fx::NONE }),
    // ---- Wisdom Path (2) ----
    syn!(30, 2, "Thought Acceleration", "Faster thoughts, cooler arts.", &["Star Thought Gu", "Fast Thought Gu"], Fx { essence_regen: 1.5, speed: 1.05, ..Fx::NONE }),
    syn!(31, 2, "Weak Spot Insight", "See the cracks; split them open.", &["Clear Mind Gu", "Deduce Gu"], Fx { crit: 0.08, ..Fx::NONE }),
    syn!(32, 2, "Mental Barrier", "Charges harden into a mind-wall.", &["Calm Thought Gu", "Wise Light Gu"], Fx { guard: 0.92, essence_max: 10.0, ..Fx::NONE }),
    syn!(33, 2, "Calculated Evasion", "Vectors solved; one free dodge.", &["Perception Gu", "Fast Thought Gu"], Fx { dodge: 0.06, ..Fx::NONE }),
    syn!(34, 2, "Malicious Infection", "Confusion spreads strike to strike.", &["Malicious Thought Gu", "Connect Mind Gu"], Fx { power: 1.10, crit: 0.03, ..Fx::NONE }),
    syn!(35, 2, "Star Ocean Processing", "Auto-targeting homing starfire.", &["Star Thought Gu", "Fast Thought Gu", "Deduce Gu"], Fx { homing: 1.5, crit: 0.04, ..Fx::NONE }),
    syn!(36, 2, "Mind Shatter", "A shockwave that shakes loot loose.", &["Thought Wave Gu", "Malicious Thought Gu", "Mind Reading Gu"], Fx { power: 1.15, gold: 1.20, ..Fx::NONE }),
    syn!(37, 2, "Deductive Counter", "Read the boss; punish the whiff.", &["Deduce Gu", "Scheme Gu", "Wise Light Gu"], Fx { crit: 0.08, dodge: 0.05, ..Fx::NONE }),
    syn!(38, 2, "Cognitive Overload", "Elites turn on their allies.", &["Cognition Gu", "Deep Thought Gu", "False Thought Gu"], Fx { power: 1.18, ..Fx::NONE }),
    syn!(39, 2, "Wisdom Domain", "An aura of bottomless clarity.", &["Wisdom Heart Gu", "Calm Thought Gu", "Delightful Thought Gu"], Fx { essence_regen: 3.0, guard: 0.93, ..Fx::NONE }),
    syn!(40, 2, "Tactician's Overclock", "Stacks into overwhelming precision.", &["Star Thought Gu", "Fast Thought Gu", "Deduce Gu", "Unravel Mystery Gu"], Fx { crit: 0.12, speed: 1.12, power: 1.12, ..Fx::NONE }),
    syn!(41, 2, "Scheme of the Heavenly Mind", "Every secret laid bare at entry.", &["Heavenly Secret Gu", "Scheme Gu", "Calculation Gu", "Mind Light Gu"], Fx { magnet: 5.0, xp: 1.25, ..Fx::NONE }),
    syn!(42, 2, "Infinite Thought Engine", "Overflow becomes orbiting fire.", &["Star Thought Gu", "Delightful Thought Gu", "Deep Thought Gu", "Thought Wave Gu"], Fx { arrows: 1, power: 1.15, ..Fx::NONE }),
    syn!(43, 2, "Pure Mind Sanctuary", "Projectiles die on the silence.", &["Clear Mind Gu", "Wisdom Seal Gu", "Wise Light Gu", "Wisdom Heart Gu"], Fx { guard: 0.85, thorns: 0.20, ..Fx::NONE }),
    syn!(44, 2, "Cognitive Suppression", "Thought-swords punish casters.", &["Cognition Gu", "Wisdom Sword Gu", "False Thought Gu", "Mind Reading Gu"], Fx { power: 1.25, crit: 0.05, ..Fx::NONE }),
    syn!(45, 2, "Omniscient Deduction", "The fight, solved in one stroke.", &["Heavenly Secret Gu", "Unravel Mystery Gu", "Wisdom Sword Gu", "Cognition Gu", "Calculation Gu"], Fx { power: 1.40, crit: 0.10, ..Fx::NONE }),
    syn!(46, 2, "Grandmaster Mindscape", "Their time crawls; yours flies.", &["Wisdom Heart Gu", "Star Thought Gu", "Delightful Thought Gu", "Wise Light Gu", "Thought Wave Gu"], Fx { power: 1.30, speed: 1.20, ..Fx::NONE }),
    syn!(47, 2, "Focused Intent", "One foe, no witnesses, +20% ruin.", &["Heart's Intent Gu", "Clear Mind Gu"], Fx { power: 1.12, ..Fx::NONE }),
    syn!(48, 2, "Thought Mirror", "A decoy drinks three shots.", &["False Thought Gu", "Mind Light Gu"], Fx { guard: 0.93, dodge: 0.03, ..Fx::NONE }),
    syn!(49, 2, "Emotional Burst", "Joy outruns everything.", &["Emotion Gu", "Delightful Thought Gu"], Fx { speed: 1.12, essence_regen: 1.0, ..Fx::NONE }),
    syn!(50, 2, "Calculated Precision", "The slowed die spectacularly.", &["Calculation Gu", "Deduce Gu", "Perception Gu"], Fx { crit: 0.09, power: 1.08, ..Fx::NONE }),
    syn!(51, 2, "Psychic Feedback", "Their blows answer themselves.", &["Thought Wave Gu", "Connect Mind Gu", "Calm Thought Gu"], Fx { thorns: 0.30, power: 1.08, ..Fx::NONE }),
    syn!(52, 2, "Mind Cleansing", "Debuffs become armor.", &["Clear Mind Gu", "Wisdom Seal Gu", "Wise Light Gu"], Fx { guard: 0.90, regen: 0.5, ..Fx::NONE }),
    syn!(53, 2, "Star-Dappled Mind", "Lit dark, longer reach.", &["Star Thought Gu", "Wise Light Gu", "Mind Light Gu"], Fx { range: 1.25, crit: 0.04, ..Fx::NONE }),
    syn!(54, 2, "Wisdom Surge", "Crits cool the arts.", &["Delightful Thought Gu", "Fast Thought Gu", "Scheme Gu", "Calculation Gu"], Fx { essence_regen: 3.0, crit: 0.06, ..Fx::NONE }),
    syn!(55, 2, "Illusory Scheme", "Ranged foes shoot each other.", &["False Thought Gu", "Scheme Gu", "Perception Gu", "Connect Mind Gu"], Fx { power: 1.20, dodge: 0.05, ..Fx::NONE }),
    syn!(56, 2, "Memory Recall", "The last art, free, again.", &["Memory Gu", "Clear Mind Gu"], Fx { essence_regen: 2.0, essence_max: 15.0, ..Fx::NONE }),
    syn!(57, 2, "Strategic Shift", "Dashes seed slowing snares.", &["Scheme Gu", "Fast Thought Gu", "Perception Gu"], Fx { speed: 1.10, dodge: 0.04, ..Fx::NONE }),
    syn!(58, 2, "Mental Fortitude", "Unstoppable casting.", &["Wisdom Heart Gu", "Calm Thought Gu", "Wise Light Gu", "Heart's Intent Gu"], Fx { guard: 0.90, max_hp: 1.10, ..Fx::NONE }),
    syn!(59, 2, "Supreme Deduction Realm", "Steal their best shot at double.", &["Unravel Mystery Gu", "Deduce Gu", "Star Thought Gu", "Heavenly Secret Gu", "Wisdom Sword Gu"], Fx { power: 1.38, range: 1.20, ..Fx::NONE }),
    // ---- Food Path (8) ----
    syn!(60, 8, "Quick Snack", "Crumbs find you more often.", &["Snack Gu", "Appetite Gu"], Fx { magnet: 2.0, gold: 1.08, ..Fx::NONE }),
    syn!(61, 8, "Purified Brew", "Every drop restores half again.", &["Liquor Worm", "Water Wine Gu"], Fx { potion: 1.35, regen: 0.3, ..Fx::NONE }),
    syn!(62, 8, "Heavy Digestion", "A full gut is armor.", &["Iron Stomach Gu", "Digestion Gu"], Fx { guard: 0.93, max_hp: 1.08, ..Fx::NONE }),
    syn!(63, 8, "Sweet Fortitude", "Desserts knit flesh for seconds.", &["Sweetness Gu", "Gourmet Gu"], Fx { regen: 0.8, potion: 1.15, ..Fx::NONE }),
    syn!(64, 8, "Spicy Burst", "Eating detonates the table.", &["Spiciness Gu", "Appetite Gu"], Fx { power: 1.12, thorns: 0.15, ..Fx::NONE }),
    syn!(65, 8, "Gluttonous Engine", "Drops become strength, arts run cheap.", &["Iron Stomach Gu", "Eat Strength Gu", "Liquor Worm"], Fx { power: 1.15, essence_regen: 1.5, ..Fx::NONE }),
    syn!(66, 8, "Feast of Plenty", "A table that buffs the room.", &["Feast Gu", "Banquet Gu", "Food Storage Gu"], Fx { max_hp: 1.12, power: 1.10, ..Fx::NONE }),
    syn!(67, 8, "Gourmet Shield", "Spare healing hardens overhead.", &["Gourmet Gu", "Big Belly Gu", "Satiation Gu"], Fx { shieldkill: 5.0, guard: 0.93, ..Fx::NONE }),
    syn!(68, 8, "Spicy Cleave", "Burning backhands that launch.", &["Spiciness Gu", "Eat Strength Gu", "Cook Gu"], Fx { power: 1.18, ..Fx::NONE }),
    syn!(69, 8, "Potion Distillation", "Floor scraps become permanent gains.", &["Wine Essence Gu", "Wine Cup Gu", "Liquor Worm"], Fx { potion: 1.40, xp: 1.15, ..Fx::NONE }),
    syn!(70, 8, "Gluttonous Berserker", "Eat, stack, double, endure.", &["Iron Stomach Gu", "Eat Strength Gu", "Liquor Worm", "Satiation Gu"], Fx { power: 1.28, guard: 0.92, ..Fx::NONE }),
    syn!(71, 8, "Elemental Seasoning", "Every bite a different burn.", &["Sweetness Gu", "Sourness Gu", "Bitterness Gu", "Spiciness Gu"], Fx { power: 1.20, crit: 0.05, ..Fx::NONE }),
    syn!(72, 8, "Master Chef's Domain", "Drops cook themselves mid-fight.", &["Cook Gu", "Gourmet Gu", "Food Refinement Gu", "Feast Gu"], Fx { gold: 1.30, xp: 1.20, ..Fx::NONE }),
    syn!(73, 8, "Ironclad Digestion", "Poison becomes lunch.", &["Iron Stomach Gu", "Big Belly Gu", "Digestion Gu", "Fasting Gu"], Fx { guard: 0.88, regen: 0.8, ..Fx::NONE }),
    syn!(74, 8, "Heavenly Banquet", "Bosses serve your coronation.", &["Heavenly Feast Gu", "Immortal Wine Gu", "Gourmet Gu", "Satiation Gu"], Fx { max_hp: 1.20, regen: 1.5, essence_max: 20.0, ..Fx::NONE }),
    syn!(75, 8, "Gluttonous Sovereign", "Eat ten foes; wear enormity.", &["Cook Gu", "Eat Strength Gu", "Iron Stomach Gu", "Heavenly Feast Gu", "Satiation Gu"], Fx { power: 1.35, range: 1.25, max_hp: 1.15, ..Fx::NONE }),
    syn!(76, 8, "Immortal Brewery", "A minute of godhood, hourly.", &["Liquor Worm", "Wine Essence Gu", "Wine Cup Gu", "Immortal Wine Gu", "Water Wine Gu"], Fx { essence_regen: 4.0, crit: 0.12, ..Fx::NONE }),
    syn!(77, 8, "Biting Sourness", "Sour bites strip their hide.", &["Sourness Gu", "Appetite Gu"], Fx { power: 1.08, ..Fx::NONE }),
    syn!(78, 8, "Bitter Resilience", "Near death tastes like iron.", &["Bitterness Gu", "Fasting Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(79, 8, "Food Gathering Surge", "The floor leans toward you.", &["Food Gathering Gu", "Food Storage Gu"], Fx { magnet: 4.0, ..Fx::NONE }),
    syn!(80, 8, "Taste Shockwave", "A pulse that ruins casting.", &["Taste Gu", "Spiciness Gu", "Bitterness Gu"], Fx { power: 1.12, speed: 1.05, ..Fx::NONE }),
    syn!(81, 8, "Satiated Bulwark", "Stillness digests into health.", &["Satiation Gu", "Big Belly Gu", "Food Storage Gu"], Fx { regen: 1.2, guard: 0.94, ..Fx::NONE }),
    syn!(82, 8, "Glutton's Strike", "Full HP hits like a cart.", &["Eat Strength Gu", "Appetite Gu", "Big Belly Gu"], Fx { power: 1.18, max_hp: 1.08, ..Fx::NONE }),
    syn!(83, 8, "Wine Spray", "A cone begging for a spark.", &["Water Wine Gu", "Wine Cup Gu", "Spiciness Gu"], Fx { range: 1.20, power: 1.10, ..Fx::NONE }),
    syn!(84, 8, "Fasting Mastery", "Hunger is haste.", &["Fasting Gu", "Iron Stomach Gu", "Digestion Gu", "Satiation Gu"], Fx { speed: 1.14, power: 1.10, ..Fx::NONE }),
    syn!(85, 8, "Banquet of Distraction", "They queue for food, not murder.", &["Banquet Gu", "Delicious Gu", "Food Gathering Gu", "Snack Gu"], Fx { dodge: 0.08, ..Fx::NONE }),
    syn!(86, 8, "Resourceful Palate", "Buffs that outstay their welcome.", &["Delicious Gu", "Taste Gu"], Fx { potion: 1.25, regen: 0.4, ..Fx::NONE }),
    syn!(87, 8, "Wine Essence Burst", "Potions pop the crowd back.", &["Wine Essence Gu", "Liquor Worm", "Appetite Gu"], Fx { thorns: 0.25, potion: 1.20, ..Fx::NONE }),
    syn!(88, 8, "Nutritional Overcharge", "Spare health becomes spare murder.", &["Gourmet Gu", "Food Refinement Gu", "Digestion Gu", "Eat Strength Gu"], Fx { power: 1.25, lifesteal: 0.03, ..Fx::NONE }),
    syn!(89, 8, "Supreme Gluttony Realm", "Eat their bullets; wear the storm.", &["Heavenly Feast Gu", "Iron Stomach Gu", "Cook Gu", "Eat Strength Gu", "Immortal Wine Gu"], Fx { guard: 0.80, power: 1.30, essence_regen: 3.0, ..Fx::NONE }),
];
