//! Canon set synergies: Theft (90-119), Qi (120-149), Enslavement (150-179).

use super::{Fx, SynergyDef};

pub const SY_B: &[SynergyDef] = &[
    // ---- Theft Path (9) ----
    syn!(90, 9, "Lightfoot Stealth", "Walls hide you; backs pay triple.", &["Silent Footstep Gu", "Sneak Attack Gu"], Fx { crit: 0.08, speed: 1.08, ..Fx::NONE }),
    syn!(91, 9, "Pocket Swipe", "Every cut lifts coin.", &["Pickpocket Gu", "Thief Hand Gu"], Fx { gold: 1.20, ..Fx::NONE }),
    syn!(92, 9, "Essence Siphon", "Hits drink their fuel tank.", &["Steal Essence Gu", "Steal Primeval Gu"], Fx { essence_regen: 2.0, essence_max: 15.0, ..Fx::NONE }),
    syn!(93, 9, "Concealed Step", "Half their eyes, twice your options.", &["Concealment Gu", "Concealed Track Gu"], Fx { dodge: 0.07, speed: 1.05, ..Fx::NONE }),
    syn!(94, 9, "Vision Thief", "Blind them; outrun the dark.", &["Steal Vision Gu", "Shadowless Thief Gu"], Fx { dodge: 0.05, speed: 1.08, ..Fx::NONE }),
    syn!(95, 9, "Void Extraction", "Backstab, drain, no reprisal.", &["Concealment Gu", "Pickpocket Gu", "Steal Essence Gu"], Fx { crit: 0.07, essence_regen: 1.5, gold: 1.15, ..Fx::NONE }),
    syn!(96, 9, "Shadow Heist", "A decoy takes your beating.", &["Shadowless Thief Gu", "Concealed Track Gu", "Thief Shadow Gu"], Fx { guard: 0.90, dodge: 0.05, ..Fx::NONE }),
    syn!(97, 9, "Thieving Strike", "Wear their speed for 8 seconds.", &["Thief Hand Gu", "Steal Thought Gu", "Steal Light Gu"], Fx { speed: 1.12, power: 1.10, ..Fx::NONE }),
    syn!(98, 9, "Soundless Dash", "Dash through; leave no rumor.", &["Silent Footstep Gu", "Concealment Gu", "Sneak Attack Gu"], Fx { speed: 1.10, crit: 0.05, ..Fx::NONE }),
    syn!(99, 9, "Pocket Extraction", "Elites misplace their weapons.", &["Pocket Steal Gu", "Plunder Gu", "Steal Form Gu"], Fx { power: 1.16, gold: 1.15, ..Fx::NONE }),
    syn!(100, 9, "Phantom Rogue Set", "Unseen in, rich out, cooled down.", &["Concealment Gu", "Silent Footstep Gu", "Pickpocket Gu", "Steal Essence Gu"], Fx { crit: 0.09, essence_regen: 2.5, gold: 1.20, ..Fx::NONE }),
    syn!(101, 9, "Master Thief's Vault", "Boss buffs look better on you.", &["Thievish Hand Gu", "Steal Dao Gu", "Plunder Gu", "Shadowless Thief Gu"], Fx { power: 1.25, gold: 1.25, ..Fx::NONE }),
    syn!(102, 9, "Spatial Robbery", "Trade places with their doom.", &["Steal Space Gu", "Steal Time Gu", "Steal Sky Gu", "Steal Earth Gu"], Fx { dodge: 0.10, speed: 1.10, ..Fx::NONE }),
    syn!(103, 9, "Silent Ghost", "Permanent whisper; smoky exits.", &["Concealment Gu", "Silent Footstep Gu", "Concealed Track Gu", "Steal Shadow Gu"], Fx { dodge: 0.09, speed: 1.12, ..Fx::NONE }),
    syn!(104, 9, "Soul Robber", "The wounded fund your arts.", &["Steal Soul Gu", "Steal Life Gu", "Steal Heart Gu", "Phantom Hand Gu"], Fx { essence_regen: 3.0, lifesteal: 0.05, ..Fx::NONE }),
    syn!(105, 9, "Great Heist Domain", "Five seconds; their shields are yours.", &["Steal Life Gu", "Steal Dao Gu", "Thievish Hand Gu", "Steal Space Gu", "Steal Time Gu"], Fx { power: 1.35, guard: 0.90, ..Fx::NONE }),
    syn!(106, 9, "Void Mirage Army", "Four hands steal as you strike.", &["Shadowless Thief Gu", "Thief Shadow Gu", "Concealment Gu", "Steal Form Gu", "Phantom Hand Gu"], Fx { power: 1.28, gold: 1.40, ..Fx::NONE }),
    syn!(107, 9, "Sound Thief", "Small silence, no castings.", &["Steal Sound Gu", "Concealment Gu"], Fx { guard: 0.94, ..Fx::NONE }),
    syn!(108, 9, "Light Thief", "Your dark, your speed.", &["Steal Light Gu", "Steal Shadow Gu"], Fx { speed: 1.12, dodge: 0.04, ..Fx::NONE }),
    syn!(109, 9, "Shadow Snare", "Stealth breaks into roots.", &["Thief Shadow Gu", "Sneak Attack Gu"], Fx { crit: 0.06, ..Fx::NONE }),
    syn!(110, 9, "Thought Extraction", "Cancelled spells fund yours.", &["Steal Thought Gu", "Pickpocket Gu", "Steal Essence Gu"], Fx { essence_regen: 2.0, power: 1.08, ..Fx::NONE }),
    syn!(111, 9, "Plunder Surge", "Theft kills cool the arts.", &["Plunder Gu", "Steal Essence Gu", "Steal Primeval Gu"], Fx { essence_regen: 2.5, gold: 1.15, ..Fx::NONE }),
    syn!(112, 9, "Phantom Hand Strike", "Shots ignore shields.", &["Phantom Hand Gu", "Thief Hand Gu", "Sneak Attack Gu"], Fx { range: 1.20, crit: 0.05, ..Fx::NONE }),
    syn!(113, 9, "Concealed Strike", "Backs break into stun.", &["Concealment Gu", "Steal Heart Gu", "Sneak Attack Gu"], Fx { crit: 0.09, ..Fx::NONE }),
    syn!(114, 9, "Essence Drain Aura", "Melee range pays tribute.", &["Steal Essence Gu", "Steal Primeval Gu", "Steal Life Gu", "Plunder Gu"], Fx { lifesteal: 0.06, essence_regen: 2.0, ..Fx::NONE }),
    syn!(115, 9, "Grand Extraction", "Elite armor, 5% at a time.", &["Steal Dao Gu", "Thievish Hand Gu", "Steal Form Gu", "Pickpocket Gu"], Fx { power: 1.25, ..Fx::NONE }),
    syn!(116, 9, "Swift Pickpocket", "Theft is cardio.", &["Pickpocket Gu", "Silent Footstep Gu"], Fx { speed: 1.10, gold: 1.12, ..Fx::NONE }),
    syn!(117, 9, "Shadow Steal", "Their shadow fights for you.", &["Steal Shadow Gu", "Concealment Gu", "Thief Shadow Gu"], Fx { guard: 0.92, dodge: 0.04, ..Fx::NONE }),
    syn!(118, 9, "Void Barrier", "Crits buy distance and a decoy.", &["Steal Space Gu", "Concealment Gu", "Concealed Track Gu", "Sneak Attack Gu"], Fx { guard: 0.90, speed: 1.08, ..Fx::NONE }),
    syn!(119, 9, "Absolute Extraction Domain", "Hazards become your aura.", &["Steal Sky Gu", "Steal Earth Gu", "Steal Life Gu", "Steal Dao Gu", "Thievish Hand Gu"], Fx { power: 1.32, gold: 1.35, guard: 0.90, ..Fx::NONE }),
    // ---- Qi Path (0) ----
    syn!(120, 0, "Air Push", "Broad cone, shoved-back melee.", &["Qi Gathering Gu", "Qi Wave Gu"], Fx { range: 1.15, power: 1.05, ..Fx::NONE }),
    syn!(121, 0, "Gaseous Shield", "Gas drinks ranged fire.", &["Qi Shield Gu", "Qi Armor Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(122, 0, "Pressure Wall", "Air that walks back.", &["Qi Wall Gu", "Qi Current Gu"], Fx { guard: 0.93, thorns: 0.10, ..Fx::NONE }),
    syn!(123, 0, "Focused Air Arrow", "Blasts that pierce the first.", &["Qi Arrow Gu", "Qi Blade Gu"], Fx { range: 1.15, power: 1.08, ..Fx::NONE }),
    syn!(124, 0, "Thermal Draft", "Updraft parks the small fry.", &["Cold Qi Gu", "Warm Qi Gu"], Fx { dodge: 0.05, regen: 0.4, ..Fx::NONE }),
    syn!(125, 0, "Implosion Zone", "Box them; pop the box.", &["Qi Gathering Gu", "Qi Wall Gu", "Qi Explosion Gu"], Fx { power: 1.22, ..Fx::NONE }),
    syn!(126, 0, "Sky Wall Fortress", "No bullets in; armor up inside.", &["Qi Wall Gu", "Qi Armor Gu", "Qi Shield Gu"], Fx { guard: 0.85, ..Fx::NONE }),
    syn!(127, 0, "Blade Torrent", "A room-wide razor storm.", &["Sword Qi Gu", "Blade Qi Gu", "Qi Wave Gu"], Fx { arrows: 2, power: 1.10, ..Fx::NONE }),
    syn!(128, 0, "Righteous Burst", "Double ruin on the unholy.", &["Righteous Qi Gu", "Dominant Qi Gu", "Qi Explosion Gu"], Fx { power: 1.22, crit: 0.04, ..Fx::NONE }),
    syn!(129, 0, "Vital Flow", "Stillness breathes essence back.", &["Vital Qi Gu", "Qi Breath Gu", "Qi Flow Gu"], Fx { essence_regen: 2.5, regen: 0.5, ..Fx::NONE }),
    syn!(130, 0, "Atmospheric Compression Set", "Aura, squeeze, seal, detonate.", &["Qi Gathering Gu", "Qi Flow Gu", "Qi Wall Gu", "Qi Explosion Gu"], Fx { power: 1.30, range: 1.15, ..Fx::NONE }),
    syn!(131, 0, "Primordial Overlord", "Eight seconds of free ruin.", &["Primordial Qi Gu", "Qi Grandmaster Gu", "Qi Sea Gu", "Mainstream Qi Gu"], Fx { power: 1.30, essence_regen: 4.0, ..Fx::NONE }),
    syn!(132, 0, "Turbulent Storm", "A tornado does your crowd work.", &["Qi Current Gu", "Cloud Qi Gu", "Qi Flow Gu", "Qi Wave Gu"], Fx { power: 1.22, magnet: 3.0, ..Fx::NONE }),
    syn!(133, 0, "Dual Qi Imbalance", "Sip life, then execute.", &["Killing Qi Gu", "Vital Qi Gu", "Death Qi Gu", "Righteous Qi Gu"], Fx { lifesteal: 0.06, crit: 0.08, ..Fx::NONE }),
    syn!(134, 0, "Domain of Absolute Pressure", "Gravity benches the room.", &["Qi Domain Gu", "Heaven-Earth Qi Gu", "Dominant Qi Gu", "Qi Form Gu"], Fx { guard: 0.85, power: 1.15, ..Fx::NONE }),
    syn!(135, 0, "Heaven-Earth Primordial Blast", "True damage, no bullets left.", &["Primordial Qi Gu", "Qi Grandmaster Gu", "Qi Sea Gu", "Heaven-Earth Qi Gu", "Qi Explosion Gu"], Fx { power: 1.40, range: 1.20, ..Fx::NONE }),
    syn!(136, 0, "Formless Atmospheric Avatar", "Ten seconds of weather.", &["Qi Form Gu", "Qi Sea Gu", "Dominant Qi Gu", "Mainstream Qi Gu", "Qi Grandmaster Gu"], Fx { guard: 0.75, speed: 1.20, ..Fx::NONE }),
    syn!(137, 0, "Deathly Breath", "Clouds that starve healing.", &["Death Qi Gu", "Qi Breath Gu"], Fx { power: 1.10, ..Fx::NONE }),
    syn!(138, 0, "Gathering Wind", "Pickups ride your casting.", &["Qi Gathering Gu", "Qi Flow Gu"], Fx { magnet: 3.0, essence_regen: 1.0, ..Fx::NONE }),
    syn!(139, 0, "Defensive Wave", "Blocks answer in shockwaves.", &["Qi Shield Gu", "Qi Wave Gu"], Fx { guard: 0.92, thorns: 0.15, ..Fx::NONE }),
    syn!(140, 0, "Blade Blast", "Impacts shred into shrapnel.", &["Blade Qi Gu", "Qi Explosion Gu", "Qi Arrow Gu"], Fx { arrows: 1, power: 1.12, ..Fx::NONE }),
    syn!(141, 0, "Righteous Barrier", "A wall that bills the sender.", &["Righteous Qi Gu", "Qi Wall Gu", "Qi Shield Gu"], Fx { guard: 0.88, thorns: 0.20, ..Fx::NONE }),
    syn!(142, 0, "Vitality Draft", "Warm currents knit flesh.", &["Vital Qi Gu", "Warm Qi Gu", "Qi Breath Gu"], Fx { regen: 1.0, ..Fx::NONE }),
    syn!(143, 0, "Cloud Cover", "Fog is a 25% miss for them.", &["Cloud Qi Gu", "Qi Form Gu", "Qi Shield Gu"], Fx { dodge: 0.07, guard: 0.95, ..Fx::NONE }),
    syn!(144, 0, "Storm Execution", "The wounded die twice.", &["Killing Qi Gu", "Sword Qi Gu", "Dominant Qi Gu", "Qi Explosion Gu"], Fx { power: 1.25, crit: 0.08, ..Fx::NONE }),
    syn!(145, 0, "Oceanic Surge", "Splash damage, endlessly.", &["Qi Sea Gu", "Qi Current Gu", "Qi Flow Gu", "Qi Wave Gu"], Fx { power: 1.20, range: 1.15, ..Fx::NONE }),
    syn!(146, 0, "Quick Breath", "Stamina can't keep up with you.", &["Qi Breath Gu", "Qi Flow Gu"], Fx { essence_regen: 2.0, speed: 1.06, ..Fx::NONE }),
    syn!(147, 0, "Dominant Shield", "Unbroken ward, unstoppable you.", &["Dominant Qi Gu", "Qi Shield Gu", "Qi Armor Gu"], Fx { guard: 0.86, ..Fx::NONE }),
    syn!(148, 0, "Cold Snap", "Walls become freezers.", &["Cold Qi Gu", "Qi Wave Gu", "Qi Wall Gu", "Qi Explosion Gu"], Fx { power: 1.22, range: 1.10, ..Fx::NONE }),
    syn!(149, 0, "Supreme Primordial Realm", "Their physics, your toy.", &["Primordial Qi Gu", "Qi Domain Gu", "Heaven-Earth Qi Gu", "Qi Grandmaster Gu", "Qi Form Gu"], Fx { power: 1.35, guard: 0.88, speed: 1.10, ..Fx::NONE }),
    // ---- Enslavement Path (1) ----
    syn!(150, 1, "Beast Command", "Louder beasts, harder bites.", &["Beast Enslavement Gu", "Enslavement Intent Gu"], Fx { power: 1.10, ..Fx::NONE }),
    syn!(151, 1, "Pack Tactics", "Every dog quickens the pack.", &["Wolf Enslavement Gu", "Dog Enslavement Gu"], Fx { speed: 1.08, power: 1.06, ..Fx::NONE }),
    syn!(152, 1, "Aerial Recon", "Wings spot throats.", &["Eagle Enslavement Gu", "Bird Enslavement Gu"], Fx { crit: 0.07, range: 1.10, ..Fx::NONE }),
    syn!(153, 1, "Beast Guard", "Big bodies take your hits.", &["Bear Enslavement Gu", "Bull Enslavement Gu"], Fx { guard: 0.92, max_hp: 1.08, ..Fx::NONE }),
    syn!(154, 1, "Swarm Control", "Dozens of teeth, all cheap.", &["Insect Enslavement Gu", "Rat Enslavement Gu"], Fx { thorns: 0.20, power: 1.06, ..Fx::NONE }),
    syn!(155, 1, "Subjugation March", "Beast, man, dragon — all kneel.", &["Beast Enslavement Gu", "Man Enslavement Gu", "Dragon Enslavement Gu"], Fx { power: 1.20, ..Fx::NONE }),
    syn!(156, 1, "Sovereign's Command", "All claws, one throat.", &["Enslavement Command Gu", "Group Control Gu", "Enslavement Mark Gu"], Fx { power: 1.18, speed: 1.08, ..Fx::NONE }),
    syn!(157, 1, "Draconic Tide", "Mythics deal in splash.", &["Dragon Enslavement Gu", "Qilin Enslavement Gu", "Phoenix Enslavement Gu"], Fx { power: 1.22, range: 1.10, ..Fx::NONE }),
    syn!(158, 1, "Avian Storm", "Rain, blindness, feathers.", &["Eagle Enslavement Gu", "Bat Enslavement Gu", "Bird Enslavement Gu"], Fx { arrows: 1, crit: 0.05, ..Fx::NONE }),
    syn!(159, 1, "Apex Predator", "Shredded armor, launched bodies.", &["Tiger Enslavement Gu", "Bear Enslavement Gu", "Elephant Enslavement Gu"], Fx { power: 1.22, ..Fx::NONE }),
    syn!(160, 1, "Beast Vanguard", "More beasts, faster, unkillable.", &["Beast Enslavement Gu", "Myriad Beast Enslavement Gu", "Enslavement Command Gu", "Group Control Gu"], Fx { power: 1.25, speed: 1.12, guard: 0.93, ..Fx::NONE }),
    syn!(161, 1, "Human Legion", "Elites die into your guard.", &["Man Enslavement Gu", "Change Soul Enslavement Gu", "Enslavement Mark Gu", "Group Control Gu"], Fx { power: 1.22, shieldkill: 4.0, ..Fx::NONE }),
    syn!(162, 1, "Swarm Extinction", "A room of venom popcorn.", &["Insect Enslavement Gu", "Rat Enslavement Gu", "Spider Enslavement Gu", "Snake Enslavement Gu"], Fx { thorns: 0.40, power: 1.12, ..Fx::NONE }),
    syn!(163, 1, "Deep-Sea Vanguard", "Flooded floors, triple fins.", &["Shark Enslavement Gu", "Crocodile Enslavement Gu", "Fish Enslavement Gu", "Dragon Enslavement Gu"], Fx { speed: 1.14, power: 1.15, ..Fx::NONE }),
    syn!(164, 1, "Mythical Sovereign", "Three lords: ward, mend, smite.", &["Qilin Enslavement Gu", "Phoenix Enslavement Gu", "Dragon Enslavement Gu", "Myriad Beast Enslavement Gu"], Fx { guard: 0.88, regen: 1.0, power: 1.15, ..Fx::NONE }),
    syn!(165, 1, "Myriad Army Extinction", "The room enslaves itself.", &["Myriad Beast Enslavement Gu", "Change Soul Enslavement Gu", "Enslavement Command Gu", "Group Control Gu", "Enslavement Mark Gu"], Fx { power: 1.40, speed: 1.10, ..Fx::NONE }),
    syn!(166, 1, "Dragon Monarch Horde", "Screen-wide dragon fire.", &["Dragon Enslavement Gu", "Qilin Enslavement Gu", "Myriad Beast Enslavement Gu", "Enslavement Command Gu", "Group Control Gu"], Fx { power: 1.35, range: 1.20, ..Fx::NONE }),
    syn!(167, 1, "Serpent Poisoning", "Strikes stack venom.", &["Snake Enslavement Gu", "Spider Enslavement Gu"], Fx { thorns: 0.15, power: 1.06, ..Fx::NONE }),
    syn!(168, 1, "Heavy Trample", "Arrivals stun the room.", &["Elephant Enslavement Gu", "Rhinoceros Enslavement Gu"], Fx { guard: 0.93, power: 1.08, ..Fx::NONE }),
    syn!(169, 1, "Fox Deception", "They hit the fox, not you.", &["Fox Enslavement Gu", "Enslavement Intent Gu"], Fx { dodge: 0.06, ..Fx::NONE }),
    syn!(170, 1, "Pack Rampage", "Speed per beast on field.", &["Wolf Enslavement Gu", "Dog Enslavement Gu", "Fox Enslavement Gu"], Fx { speed: 1.12, power: 1.10, ..Fx::NONE }),
    syn!(171, 1, "Web Snare", "The floor holds still.", &["Spider Enslavement Gu", "Insect Enslavement Gu", "Enslavement Mark Gu"], Fx { thorns: 0.25, ..Fx::NONE }),
    syn!(172, 1, "Avian Dive", "Death from a clear sky.", &["Eagle Enslavement Gu", "Bird Enslavement Gu", "Bat Enslavement Gu"], Fx { crit: 0.09, power: 1.08, ..Fx::NONE }),
    syn!(173, 1, "Shielding Horde", "Living walls stop bullets.", &["Bear Enslavement Gu", "Bull Enslavement Gu", "Elephant Enslavement Gu"], Fx { guard: 0.88, max_hp: 1.10, ..Fx::NONE }),
    syn!(174, 1, "Soul Mark Control", "The slain burst in soulfire.", &["Change Soul Enslavement Gu", "Enslavement Mark Gu", "Man Enslavement Gu", "Beast Enslavement Gu"], Fx { power: 1.22, lifesteal: 0.03, ..Fx::NONE }),
    syn!(175, 1, "Ocean Hunters", "Ranged foes dragged to teeth.", &["Shark Enslavement Gu", "Fish Enslavement Gu", "Crocodile Enslavement Gu", "Beast Enslavement Gu"], Fx { magnet: 3.0, power: 1.12, ..Fx::NONE }),
    syn!(176, 1, "Targeted Mark", "One throat, +25% everything.", &["Enslavement Mark Gu", "Enslavement Command Gu"], Fx { crit: 0.08, power: 1.06, ..Fx::NONE }),
    syn!(177, 1, "Beast Aura", "The pack runs at your pace.", &["Beast Enslavement Gu", "Enslavement Intent Gu", "Group Control Gu"], Fx { speed: 1.12, ..Fx::NONE }),
    syn!(178, 1, "Mythical Guard", "Status can't touch the guarded.", &["Qilin Enslavement Gu", "Dragon Enslavement Gu", "Enslavement Command Gu", "Group Control Gu"], Fx { guard: 0.87, max_hp: 1.10, ..Fx::NONE }),
    syn!(179, 1, "Absolute Sovereign Realm", "Their health, your shield, double fangs.", &["Myriad Beast Enslavement Gu", "Enslavement Command Gu", "Group Control Gu", "Change Soul Enslavement Gu", "Enslavement Mark Gu"], Fx { guard: 0.82, power: 1.32, ..Fx::NONE }),
];
