//! Canon set synergies: Transformation (180-209), Wood (210-239), Soul (240-269).

use super::{Fx, SynergyDef};

pub const SY_C: &[SynergyDef] = &[
    // ---- Transformation Path (3) ----
    syn!(180, 3, "Beast Hide", "Thick, rooted, unmoved.", &["Bear Skin Gu", "Fur Gu"], Fx { guard: 0.92, ..Fx::NONE }),
    syn!(181, 3, "Predator Claws", "Cuts that strip plate.", &["Tiger Claw Gu", "Lion Fur Gu"], Fx { power: 1.10, crit: 0.03, ..Fx::NONE }),
    syn!(182, 3, "Scaled Bulwark", "Plate plus fire-proofing.", &["Dragon Scales Gu", "Fish Scale Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(183, 3, "Feather Dash", "Longer dashes, burning wake.", &["Eagle Feather Gu", "Phoenix Feather Gu"], Fx { speed: 1.10, power: 1.05, ..Fx::NONE }),
    syn!(184, 3, "Serpent Agility", "Slippery and venom-proof.", &["Snake Skin Gu", "Soft Body Gu"], Fx { dodge: 0.07, ..Fx::NONE }),
    syn!(185, 3, "Beast King Chimera", "Blunt hide, razor hands.", &["Bear Skin Gu", "Tiger Claw Gu", "Change Form Gu"], Fx { guard: 0.90, power: 1.15, ..Fx::NONE }),
    syn!(186, 3, "Aquatic Transformation", "Triple fins; bites heal.", &["Shark Fin Gu", "Fish Scale Gu", "Water Transformation Gu"], Fx { speed: 1.12, lifesteal: 0.05, ..Fx::NONE }),
    syn!(187, 3, "Aerial Strike", "A slam that sits them down.", &["Eagle Feather Gu", "Bull Horn Gu", "Flying Bear Transformation Gu"], Fx { power: 1.20, ..Fx::NONE }),
    syn!(188, 3, "Fire-Scaled Drake", "A mini-dragon's commute.", &["Dragon Scales Gu", "Fire Transformation Gu", "Dragon Transformation Gu"], Fx { power: 1.22, thorns: 0.15, ..Fx::NONE }),
    syn!(189, 3, "Giant Morph", "Twice the mass, twice the reach.", &["Giant Transformation Gu", "Bone Morph Gu", "Bear Skin Gu"], Fx { power: 1.20, max_hp: 1.12, ..Fx::NONE }),
    syn!(190, 3, "Apex Chimera Form", "Tiger speed in bear mass.", &["Fur Gu", "Bear Skin Gu", "Tiger Claw Gu", "Change Form Gu"], Fx { guard: 0.90, power: 1.18, speed: 1.08, ..Fx::NONE }),
    syn!(191, 3, "Elemental Shift", "Become what doesn't hurt.", &["Water Transformation Gu", "Fire Transformation Gu", "Lightning Transformation Gu", "Shadow Transformation Gu"], Fx { guard: 0.86, ..Fx::NONE }),
    syn!(192, 3, "Flying Bear Vanguard", "Wings, mass, and bad news.", &["Flying Bear Transformation Gu", "Bear Skin Gu", "Giant Transformation Gu", "Change Form Gu"], Fx { power: 1.25, guard: 0.92, ..Fx::NONE }),
    syn!(193, 3, "Assimilation Wind Tempest", "Small body, shredding weather.", &["Assimilation Wind Transformation Gu", "Complete Change Gu", "Soft Body Gu", "Miniature Transformation Gu"], Fx { dodge: 0.09, power: 1.15, ..Fx::NONE }),
    syn!(194, 3, "Draconic Sovereign", "An ancient dragon's reserves.", &["Dragon Scales Gu", "Phoenix Feather Gu", "Dragon Transformation Gu", "Complete Change Gu"], Fx { max_hp: 1.30, power: 1.20, ..Fx::NONE }),
    syn!(195, 3, "Myriad Beings Sovereign", "Wear any foe you see.", &["Myriad Beings Transformation Gu", "Change Form Gu", "Complete Change Gu", "Giant Transformation Gu", "Miniature Transformation Gu"], Fx { power: 1.35, guard: 0.90, ..Fx::NONE }),
    syn!(196, 3, "Phoenix Rebirth Morph", "Fatal becomes feathers.", &["Phoenix Feather Gu", "Fire Transformation Gu", "Phoenix Transformation Gu", "Complete Change Gu", "Soft Body Gu"], Fx { revive: true, regen: 1.0, ..Fx::NONE }),
    syn!(197, 3, "Turtle Armor", "Backs don't bleed here.", &["Turtle Shell Gu", "Bear Skin Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(198, 3, "Wolf Pounce", "Long leaps, heavy landings.", &["Wolf Tail Gu", "Tiger Claw Gu"], Fx { speed: 1.08, power: 1.08, ..Fx::NONE }),
    syn!(199, 3, "Soft Dodge", "A third less of you to hit.", &["Soft Body Gu", "Miniature Transformation Gu"], Fx { dodge: 0.08, ..Fx::NONE }),
    syn!(200, 3, "Bone Spike Armor", "Hugs cost them pierce.", &["Bone Morph Gu", "Bear Skin Gu", "Turtle Shell Gu"], Fx { thorns: 0.30, guard: 0.92, ..Fx::NONE }),
    syn!(201, 3, "Horned Charge", "Elites relocate; walls don't.", &["Bull Horn Gu", "Giant Transformation Gu", "Change Form Gu"], Fx { power: 1.15, speed: 1.08, ..Fx::NONE }),
    syn!(202, 3, "Shadow Stalker Morph", "Shadows are hallways.", &["Shadow Transformation Gu", "Snake Skin Gu", "Soft Body Gu"], Fx { dodge: 0.08, speed: 1.06, ..Fx::NONE }),
    syn!(203, 3, "Lightning Beast", "Dashes strike like weather.", &["Lightning Transformation Gu", "Tiger Claw Gu", "Change Form Gu"], Fx { speed: 1.12, power: 1.12, ..Fx::NONE }),
    syn!(204, 3, "Beast Lord Morph", "Three forms, fresh arts each.", &["Tiger Transformation Gu", "Ape Transformation Gu", "Dragon Transformation Gu", "Complete Change Gu"], Fx { power: 1.22, essence_regen: 2.0, ..Fx::NONE }),
    syn!(205, 3, "Wind Runner Morph", "Dodges buy five seconds of wind.", &["Eagle Feather Gu", "Soft Body Gu", "Assimilation Wind Transformation Gu", "Miniature Transformation Gu"], Fx { speed: 1.16, dodge: 0.05, ..Fx::NONE }),
    syn!(206, 3, "Hardened Scales", "Pain becomes aperture fuel.", &["Fish Scale Gu", "Dragon Scales Gu"], Fx { guard: 0.93, essence_regen: 1.0, ..Fx::NONE }),
    syn!(207, 3, "Ape Strength", "The room is ammunition.", &["Ape Transformation Gu", "Giant Transformation Gu", "Bone Morph Gu"], Fx { power: 1.20, ..Fx::NONE }),
    syn!(208, 3, "Chimerical Shift", "Ailments slide off new flesh.", &["Change Form Gu", "Complete Change Gu", "Soft Body Gu", "Bone Morph Gu"], Fx { guard: 0.92, regen: 0.6, ..Fx::NONE }),
    syn!(209, 3, "Absolute Transformation Realm", "Every shape, zero cost.", &["Myriad Beings Transformation Gu", "Complete Change Gu", "Assimilation Wind Transformation Gu", "Flying Bear Transformation Gu", "Dragon Transformation Gu"], Fx { essence_regen: 4.0, power: 1.25, guard: 0.90, ..Fx::NONE }),
    // ---- Wood Path (4) ----
    syn!(210, 4, "Vine Whip", "Drag them into hugging range.", &["Spring Grass Gu", "Vine Whip Gu"], Fx { magnet: 2.0, power: 1.05, ..Fx::NONE }),
    syn!(211, 4, "Bark Armor", "Hits sprout leaf shields.", &["Wood Bark Gu", "Tree Bark Armor Gu"], Fx { guard: 0.90, shieldkill: 2.0, ..Fx::NONE }),
    syn!(212, 4, "Needle Storm", "Needles ignore shields.", &["Pine Needle Gu", "Leaf Blade Gu"], Fx { range: 1.15, power: 1.08, ..Fx::NONE }),
    syn!(213, 4, "Root Binding", "Two seconds of still life.", &["Bamboo Root Gu", "Root Bound Gu"], Fx { thorns: 0.15, power: 1.06, ..Fx::NONE }),
    syn!(214, 4, "Floral Healing", "A garden that pays in HP.", &["Healing Grass Gu", "Flower Petal Gu"], Fx { regen: 1.0, ..Fx::NONE }),
    syn!(215, 4, "Flash Garden", "Grass, walls, shredding.", &["Spring Grass Gu", "Leaf Blade Gu", "Tree Shield Gu"], Fx { thorns: 0.25, guard: 0.92, ..Fx::NONE }),
    syn!(216, 4, "Thorn Wall Bulwark", "Vines that bill the striker.", &["Thorn Gu", "Tree Bark Armor Gu", "Root Bound Gu"], Fx { thorns: 0.35, guard: 0.90, ..Fx::NONE }),
    syn!(217, 4, "Spore Poison", "Miss, miss, spores.", &["Pollen Gu", "Wood Sprouts Gu", "Wood Spirit Gu"], Fx { dodge: 0.06, power: 1.08, ..Fx::NONE }),
    syn!(218, 4, "Ancient Vitality", "One fifth more vessel.", &["Vitality Gu", "Ancient Tree Gu", "Wood Core Gu"], Fx { max_hp: 1.20, regen: 0.8, ..Fx::NONE }),
    syn!(219, 4, "Woodland Swarm", "Wooden friends catch bullets.", &["Wood Spirit Gu", "Wooden Chicken Gu", "Willow Leaf Gu"], Fx { guard: 0.92, power: 1.08, ..Fx::NONE }),
    syn!(220, 4, "Living Forest Vanguard", "Grass, razors, roots, walls.", &["Spring Grass Gu", "Leaf Blade Gu", "Bamboo Root Gu", "Tree Shield Gu"], Fx { thorns: 0.30, guard: 0.90, power: 1.10, ..Fx::NONE }),
    syn!(221, 4, "Ancient Forest Domain", "A tree that fights back.", &["Ancient Tree Gu", "Wood Essence Gu", "Divine Wood Gu", "Life Tree Gu"], Fx { regen: 1.5, power: 1.15, ..Fx::NONE }),
    syn!(222, 4, "Thornburst Fortress", "Damage out, thorns in 360.", &["Thorn Gu", "Pine Needle Gu", "Tree Bark Armor Gu", "Wood Core Gu"], Fx { thorns: 0.45, guard: 0.90, ..Fx::NONE }),
    syn!(223, 4, "Eternal Blossom", "Footsteps bloom into cures.", &["Peach Blossom Gu", "Eternal Spring Gu", "Healing Grass Gu", "Vitality Gu"], Fx { regen: 1.5, max_hp: 1.10, ..Fx::NONE }),
    syn!(224, 4, "Grass Blade Storm", "An orbital shredder ring.", &["Grass Sword Gu", "Willow Leaf Gu", "Leaf Blade Gu", "Leaf Shield Gu"], Fx { thorns: 0.35, guard: 0.90, ..Fx::NONE }),
    syn!(225, 4, "Divine Wood Realm", "Rooted foes, untouchable you.", &["Divine Wood Gu", "Life Tree Gu", "Eternal Spring Gu", "Ancient Tree Gu", "Wood Spirit Gu"], Fx { guard: 0.82, regen: 2.0, ..Fx::NONE }),
    syn!(226, 4, "Forest Fire Immunity", "Fire becomes breakfast.", &["Forest Fire Immunity Gu", "Divine Wood Gu", "Wood Core Gu", "Timber Gu", "Wood Bark Gu"], Fx { guard: 0.85, regen: 1.5, ..Fx::NONE }),
    syn!(227, 4, "Pollen Fog", "Crits buy a blinding cloud.", &["Pollen Gu", "Wood Sprouts Gu"], Fx { dodge: 0.06, ..Fx::NONE }),
    syn!(228, 4, "Woodland Shield", "First bullet's on the house.", &["Leaf Shield Gu", "Tree Shield Gu"], Fx { guard: 0.90, shieldkill: 2.0, ..Fx::NONE }),
    syn!(229, 4, "Root Trap", "Roots that bleed the bound.", &["Bamboo Root Gu", "Thorn Gu"], Fx { thorns: 0.20, lifesteal: 0.02, ..Fx::NONE }),
    syn!(230, 4, "Timber Crush", "Trunks fall where pointed.", &["Timber Gu", "Ancient Tree Gu", "Wood Core Gu"], Fx { power: 1.18, ..Fx::NONE }),
    syn!(231, 4, "Vitality Surge", "Tonics quicken the feet.", &["Vitality Gu", "Wood Sprouts Gu", "Healing Grass Gu"], Fx { speed: 1.10, regen: 0.6, ..Fx::NONE }),
    syn!(232, 4, "Willow Whip", "One sweep, full circle.", &["Willow Leaf Gu", "Vine Whip Gu", "Leaf Blade Gu"], Fx { range: 1.20, power: 1.08, ..Fx::NONE }),
    syn!(233, 4, "Sprout Explosion", "The slain sprout into snacks.", &["Wood Sprouts Gu", "Spring Grass Gu", "Pollen Gu"], Fx { lifesteal: 0.04, regen: 0.5, ..Fx::NONE }),
    syn!(234, 4, "Thorned Armor", "Armor that bites neighbors.", &["Thorn Gu", "Tree Bark Armor Gu", "Wood Bark Gu", "Wood Core Gu"], Fx { guard: 0.88, thorns: 0.30, ..Fx::NONE }),
    syn!(235, 4, "Forest Guardian", "A golem takes your meeting.", &["Wood Spirit Gu", "Ancient Tree Gu", "Timber Gu", "Divine Wood Gu"], Fx { guard: 0.88, max_hp: 1.12, ..Fx::NONE }),
    syn!(236, 4, "Leaf Dash", "Dashes seed slowing trails.", &["Willow Leaf Gu", "Flower Petal Gu"], Fx { speed: 1.10, ..Fx::NONE }),
    syn!(237, 4, "Wood Essence Regeneration", "Dealt pain returns as health.", &["Wood Essence Gu", "Vitality Gu", "Wood Core Gu"], Fx { lifesteal: 0.05, ..Fx::NONE }),
    syn!(238, 4, "Spring Barrier", "Four seconds of healing peace.", &["Eternal Spring Gu", "Life Tree Gu", "Tree Shield Gu", "Healing Grass Gu"], Fx { guard: 0.85, regen: 1.2, ..Fx::NONE }),
    syn!(239, 4, "Supreme Forest Domain", "Furniture with allegiances.", &["Divine Wood Gu", "Life Tree Gu", "Eternal Spring Gu", "Ancient Tree Gu", "Wood Essence Gu"], Fx { arrows: 2, power: 1.20, regen: 1.0, ..Fx::NONE }),
    // ---- Soul Path (5) ----
    syn!(240, 5, "Soul Shock", "Crits stun the mind.", &["Soul Light Gu", "Soul Shaking Gu"], Fx { crit: 0.06, ..Fx::NONE }),
    syn!(241, 5, "Spectral Armor", "Ghosts guard their own.", &["Soul Armor Gu", "Soul Shield Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(242, 5, "Soul Wail", "A scream that tires arms.", &["Soul Howl Gu", "Soul Sound Gu"], Fx { guard: 0.93, power: 1.05, ..Fx::NONE }),
    syn!(243, 5, "Soul Extraction", "The slain pay essence.", &["Soul Searching Gu", "Soul Devour Gu"], Fx { essence_regen: 1.5, lifesteal: 0.03, ..Fx::NONE }),
    syn!(244, 5, "Guts Reinforcement", "Deeper foundation, thicker skin.", &["Guts Gu", "Strong Soul Gu"], Fx { max_hp: 1.10, guard: 0.95, ..Fx::NONE }),
    syn!(245, 5, "Desolate Soul Tide", "Howl, paralyze, harvest beasts.", &["Soul Howl Gu", "Soul Shaking Gu", "Soul Beast Summoning Gu"], Fx { power: 1.18, crit: 0.04, ..Fx::NONE }),
    syn!(246, 5, "Soul Cleansing", "Clean mind, spare body.", &["Cleanse Soul Gu", "Change Soul Gu", "Split Soul Gu"], Fx { guard: 0.92, dodge: 0.04, ..Fx::NONE }),
    syn!(247, 5, "Soul Trap Field", "Chained souls, thinner armor.", &["Soul Trap Gu", "Soul Chain Gu", "Soul Suppression Gu"], Fx { power: 1.15, ..Fx::NONE }),
    syn!(248, 5, "Phantom Spear", "Spears that ignore walls.", &["Soul Spear Gu", "Phantom Soul Gu", "Wandering Soul Gu"], Fx { range: 1.25, power: 1.10, ..Fx::NONE }),
    syn!(249, 5, "Soul Fire Storm", "Drained fuel becomes flesh.", &["Soul Fire Gu", "Soul Light Gu", "Soul Devour Gu"], Fx { lifesteal: 0.06, essence_regen: 1.5, ..Fx::NONE }),
    syn!(250, 5, "Soul Extinction Vanguard", "Howl to harvest, start to finish.", &["Soul Howl Gu", "Soul Shaking Gu", "Soul Searching Gu", "Soul Beast Summoning Gu"], Fx { power: 1.25, crit: 0.05, ..Fx::NONE }),
    syn!(251, 5, "Soul Devouring Monarch", "Standing near you is fatal.", &["Soul Devour Gu", "Suppress Soul Gu", "Soul Refinement Gu", "Soul Cultivation Gu"], Fx { lifesteal: 0.08, power: 1.15, ..Fx::NONE }),
    syn!(252, 5, "Spectral Mirror Shift", "Trade places; both ends boom.", &["Soul Mirror Gu", "Soul Unity Gu", "Phantom Soul Gu", "Soul Shift Gu"], Fx { power: 1.18, dodge: 0.05, ..Fx::NONE }),
    syn!(253, 5, "Guts Soul Cleansing", "Pure body, +30% fists.", &["Guts Gu", "Cleanse Soul Gu", "Strong Soul Gu", "Soul Refinement Gu"], Fx { power: 1.25, max_hp: 1.10, ..Fx::NONE }),
    syn!(254, 5, "Wandering Phantom Legion", "Three ghosts, fiery exits.", &["Wandering Soul Gu", "Soul Mark Gu", "Split Soul Gu", "Soul Beast Summoning Gu"], Fx { power: 1.22, ..Fx::NONE }),
    syn!(255, 5, "Spectral Soul Realm", "Small souls, repossessed.", &["Suppress Soul Gu", "Soul Devour Gu", "Cleanse Soul Gu", "Change Soul Gu", "Soul Unity Gu"], Fx { power: 1.35, lifesteal: 0.06, ..Fx::NONE }),
    syn!(256, 5, "Immortal Soul Sovereign", "Crits buy eight godless seconds.", &["Guts Gu", "Strong Soul Gu", "Soul Refinement Gu", "Soul Cultivation Gu", "Cleanse Soul Gu"], Fx { guard: 0.80, max_hp: 1.15, ..Fx::NONE }),
    syn!(257, 5, "Soul Mark", "Marked ghosts take +15%.", &["Soul Mark Gu", "Soul Searching Gu"], Fx { crit: 0.06, power: 1.05, ..Fx::NONE }),
    syn!(258, 5, "Phantom Dash", "Walk through the crowd.", &["Phantom Soul Gu", "Wandering Soul Gu"], Fx { dodge: 0.06, speed: 1.06, ..Fx::NONE }),
    syn!(259, 5, "Soul Fire Shield", "Hitters catch ghostfire.", &["Soul Fire Gu", "Soul Shield Gu"], Fx { thorns: 0.25, guard: 0.94, ..Fx::NONE }),
    syn!(260, 5, "Spectral Spear Burst", "Marks pop like lanterns.", &["Soul Spear Gu", "Soul Light Gu", "Soul Mark Gu"], Fx { crit: 0.07, power: 1.10, ..Fx::NONE }),
    syn!(261, 5, "Soul Suppression Field", "Nearby arms go weak.", &["Soul Suppression Gu", "Soul Armor Gu", "Suppress Soul Gu"], Fx { guard: 0.92, power: 1.08, ..Fx::NONE }),
    syn!(262, 5, "Split Decoy", "A soul takes your place.", &["Split Soul Gu", "Phantom Soul Gu", "Soul Shift Gu"], Fx { dodge: 0.07, guard: 0.94, ..Fx::NONE }),
    syn!(263, 5, "Guts Regeneration", "Slow, endless knitting.", &["Guts Gu", "Soul Cultivation Gu", "Strong Soul Gu"], Fx { regen: 1.0, max_hp: 1.08, ..Fx::NONE }),
    syn!(264, 5, "Spectral Chain Snare", "Four foes, one knot.", &["Soul Chain Gu", "Soul Trap Gu", "Soul Suppression Gu", "Soul Shaking Gu"], Fx { power: 1.15, thorns: 0.10, ..Fx::NONE }),
    syn!(265, 5, "Soul Devouring Flame", "Kills spread the ghostfire.", &["Soul Devour Gu", "Soul Fire Gu", "Soul Refinement Gu", "Suppress Soul Gu"], Fx { power: 1.22, lifesteal: 0.04, ..Fx::NONE }),
    syn!(266, 5, "Soul Light Blind", "Casting blinds the room.", &["Soul Light Gu", "Soul Sound Gu"], Fx { dodge: 0.05, ..Fx::NONE }),
    syn!(267, 5, "Spectral Unity", "Company is armor.", &["Soul Unity Gu", "Soul Armor Gu", "Strong Soul Gu"], Fx { guard: 0.90, max_hp: 1.08, ..Fx::NONE }),
    syn!(268, 5, "Soul Shift Counter", "Answer backs with interest.", &["Soul Shift Gu", "Soul Shaking Gu", "Soul Spear Gu", "Phantom Soul Gu"], Fx { crit: 0.09, power: 1.12, ..Fx::NONE }),
    syn!(269, 5, "Supreme Soul Realm", "Soul damage becomes breakfast.", &["Suppress Soul Gu", "Soul Unity Gu", "Cleanse Soul Gu", "Soul Devour Gu", "Soul Howl Gu"], Fx { lifesteal: 0.10, regen: 1.5, ..Fx::NONE }),
];
