//! Canon set synergies: Luck (270-299), Refinement (300-329), Dream (330-359).

use super::{Fx, SynergyDef};

pub const SY_D: &[SynergyDef] = &[
    // ---- Luck Path (6) ----
    syn!(270, 6, "Fortune Inspect", "Peek inside unopened chests.", &["Inspect Luck Gu", "Notice Luck Gu"], Fx { gold: 1.15, magnet: 1.0, ..Fx::NONE }),
    syn!(271, 6, "Bad Luck Curse", "Their swings find air.", &["Bad Luck Gu", "Misfortune Gu"], Fx { dodge: 0.07, ..Fx::NONE }),
    syn!(272, 6, "Luck Shield", "One hit in seven never lands.", &["Luck Shield Gu", "Good Luck Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(273, 6, "Scatter Fortune", "Struck foes drop richer.", &["Scatter Luck Gu", "Small Luck Gu"], Fx { gold: 1.20, ..Fx::NONE }),
    syn!(274, 6, "Fortune Star", "A tenth more ruin.", &["Fortunate Star Gu", "Luck Light Gu"], Fx { crit: 0.08, ..Fx::NONE }),
    syn!(275, 6, "Dog Shit Luck Miracle", "Traps switch sides.", &["Dog Shit Luck Gu", "Connect Luck Gu", "Good Luck Gu"], Fx { dodge: 0.07, thorns: 0.20, ..Fx::NONE }),
    syn!(276, 6, "Luck Siphon", "Strip elites of fortune.", &["Steal Luck Gu", "Plunder Luck Gu", "Borrow Luck Gu"], Fx { crit: 0.08, power: 1.10, ..Fx::NONE }),
    syn!(277, 6, "Calamity Suppression", "Boss ults hit softer.", &["Calamity Suppression Gu", "Suppress Luck Gu", "Luck Shield Gu"], Fx { guard: 0.88, ..Fx::NONE }),
    syn!(278, 6, "Fortune Shift", "Next chest: jackpot.", &["Transfer Luck Gu", "Gather Luck Gu", "Fortunate Star Gu"], Fx { gold: 1.30, ..Fx::NONE }),
    syn!(279, 6, "Calamity Beckoning", "Call the sky, pay in luck.", &["Calamity Beckoning Gu", "Bad Luck Gu", "Misfortune Gu"], Fx { power: 1.25, ..Fx::NONE }),
    syn!(280, 6, "Rivaling Heaven Miracle", "Luck maxed; heaven mugged.", &["Rivaling Heaven Gu", "Dog Shit Luck Gu", "Connect Luck Gu", "Calamity Beckoning Gu"], Fx { crit: 0.12, power: 1.20, ..Fx::NONE }),
    syn!(281, 6, "Absolute Fortune Engine", "Ten seconds of yes.", &["Good Luck Gu", "Fortunate Star Gu", "Gather Luck Gu", "All Living Beings Luck Gu"], Fx { crit: 0.15, gold: 1.35, ..Fx::NONE }),
    syn!(282, 6, "Luck Curse Siphon", "Naked to triple crits.", &["Break Luck Gu", "Suppress Luck Gu", "Steal Luck Gu", "Bad Luck Gu"], Fx { crit: 0.12, power: 1.15, ..Fx::NONE }),
    syn!(283, 6, "Heaven-Earth Luck Unity", "Luck breathes you back.", &["Heaven's Luck Gu", "Earth's Luck Gu", "Qi Luck Gu", "Connect Luck Gu"], Fx { regen: 1.2, essence_regen: 2.0, ..Fx::NONE }),
    syn!(284, 6, "Immortal Luck Aegis", "Spells return to sender.", &["Immortal Luck Gu", "Luck Shield Gu", "Calamity Suppression Gu", "Good Luck Gu"], Fx { guard: 0.85, thorns: 0.25, ..Fx::NONE }),
    syn!(285, 6, "Heaven-Defying Fortune Realm", "Fifteen seconds of 1 HP.", &["Rivaling Heaven Gu", "Dog Shit Luck Gu", "Connect Luck Gu", "Calamity Beckoning Gu", "All Living Beings Luck Gu"], Fx { revive: true, guard: 0.88, ..Fx::NONE }),
    syn!(286, 6, "Calamity Redirection", "Bosses fight their own staff.", &["Calamity Beckoning Gu", "Calamity Suppression Gu", "Transfer Luck Gu", "Plunder Luck Gu", "Steal Luck Gu"], Fx { guard: 0.88, power: 1.15, ..Fx::NONE }),
    syn!(287, 6, "Small Fortune", "More drops, always.", &["Small Luck Gu", "Fortune Gu"], Fx { gold: 1.15, ..Fx::NONE }),
    syn!(288, 6, "Misfortune Aura", "Adjacency is inaccuracy.", &["Misfortune Gu", "Bad Luck Gu"], Fx { dodge: 0.06, ..Fx::NONE }),
    syn!(289, 6, "Inspect Weakness", "Low-luck targets glow.", &["Notice Luck Gu", "Luck Inspection Gu"], Fx { crit: 0.07, ..Fx::NONE }),
    syn!(290, 6, "Gathering Luck", "Clean rooms compound.", &["Gather Luck Gu", "Small Luck Gu", "Good Luck Gu"], Fx { gold: 1.18, xp: 1.15, ..Fx::NONE }),
    syn!(291, 6, "Luck Break Strike", "Elites lose their shine.", &["Break Luck Gu", "Bad Luck Gu", "Fortune Gu"], Fx { crit: 0.08, power: 1.08, ..Fx::NONE }),
    syn!(292, 6, "Borrow Fortune", "Tomorrow funds today.", &["Borrow Luck Gu", "Transfer Luck Gu", "Fortunate Star Gu"], Fx { power: 1.18, ..Fx::NONE }),
    syn!(293, 6, "Star-Crossed Luck", "Shots curve like gossip.", &["Fortunate Star Gu", "Luck Light Gu", "Qi Luck Gu"], Fx { homing: 1.5, crit: 0.04, ..Fx::NONE }),
    syn!(294, 6, "Plundered Fortune", "Strikes mint coin.", &["Plunder Luck Gu", "Steal Luck Gu", "Transfer Luck Gu", "Break Luck Gu"], Fx { gold: 1.30, power: 1.10, ..Fx::NONE }),
    syn!(295, 6, "Earthly Fortune", "Standing still pays.", &["Earth's Luck Gu", "Qi Luck Gu", "Gather Luck Gu", "Good Luck Gu"], Fx { regen: 1.0, gold: 1.15, ..Fx::NONE }),
    syn!(296, 6, "Notice Traps", "Ambushes announce themselves.", &["Notice Luck Gu", "Inspect Luck Gu"], Fx { dodge: 0.05, magnet: 1.0, ..Fx::NONE }),
    syn!(297, 6, "Luck Shield Burst", "Blocks rain currency.", &["Luck Shield Gu", "Scatter Luck Gu", "Good Luck Gu"], Fx { guard: 0.92, gold: 1.20, ..Fx::NONE }),
    syn!(298, 6, "Calamity Ward", "Mutators skip you.", &["Calamity Suppression Gu", "Luck Shield Gu", "Immortal Luck Gu", "Suppress Luck Gu"], Fx { guard: 0.87, ..Fx::NONE }),
    syn!(299, 6, "Supreme Luck Realm", "Max rolls on everything.", &["Rivaling Heaven Gu", "Immortal Luck Gu", "Heaven's Luck Gu", "Earth's Luck Gu", "All Living Beings Luck Gu"], Fx { crit: 0.15, gold: 1.30, dodge: 0.08, ..Fx::NONE }),
    // ---- Refinement Path (10) ----
    syn!(300, 10, "Fire Tempering", "Faster forge, hotter hands.", &["Refine Gu", "Fire Refinement Gu"], Fx { power: 1.10, ..Fx::NONE }),
    syn!(301, 10, "Water Quenching", "Stable crafts, mending waters.", &["Nurture Gu", "Water Refinement Gu"], Fx { regen: 0.6, power: 1.05, ..Fx::NONE }),
    syn!(302, 10, "Quick Craft", "Cooldowns cut nearly half.", &["Quick Refinement Gu", "Refine Gu"], Fx { essence_regen: 2.0, speed: 1.05, ..Fx::NONE }),
    syn!(303, 10, "Forced Alloy", "Two scraps, one treasure.", &["Force Refinement Gu", "Unify Form Gu"], Fx { gold: 1.15, power: 1.08, ..Fx::NONE }),
    syn!(304, 10, "Quiet Forge", "Hammer in peace.", &["Quiet Refinement Gu", "Auxiliary Refinement Gu"], Fx { guard: 0.94, ..Fx::NONE }),
    syn!(305, 10, "Flash Elemental Refining", "Perfect craft, zero penalty.", &["Fire Refinement Gu", "Water Refinement Gu", "Success Gu"], Fx { power: 1.15, crit: 0.04, ..Fx::NONE }),
    syn!(306, 10, "Natural Alchemy", "The floor is ingredients.", &["Natural Refinement Gu", "Earth Refinement Gu", "Heaven Refinement Gu"], Fx { gold: 1.25, regen: 0.5, ..Fx::NONE }),
    syn!(307, 10, "Batch Production", "Three for the price of one.", &["Batch Refinement Gu", "Auxiliary Refinement Gu", "Refinement Light Gu"], Fx { potion: 1.30, gold: 1.15, ..Fx::NONE }),
    syn!(308, 10, "Elemental Tempering", "Strikes carry frost and shock.", &["Ice Refinement Gu", "Lightning Refinement Gu", "Core Refinement Gu"], Fx { power: 1.15, range: 1.10, ..Fx::NONE }),
    syn!(309, 10, "Refinement Aura", "A field that mends gear.", &["Refinement Mark Gu", "Gentle Refinement Gu", "Refinement Aid Gu"], Fx { guard: 0.92, regen: 0.5, ..Fx::NONE }),
    syn!(310, 10, "Master Forge Vanguard", "Melt, temper, hurry, perfect.", &["Fire Refinement Gu", "Water Refinement Gu", "Quick Refinement Gu", "Success Gu"], Fx { power: 1.22, essence_regen: 2.0, ..Fx::NONE }),
    syn!(311, 10, "Heavenly Lotus Assembly", "Worms rank themselves up.", &["Heavenly Essence Treasure Monarch Lotus", "Refine Sea Gu", "Natural Refinement Gu", "Refine Dao Gu"], Fx { power: 1.25, xp: 1.25, ..Fx::NONE }),
    syn!(312, 10, "Elemental Refinement Matrix", "Four moods of +35% ruin.", &["Fire Refinement Gu", "Water Refinement Gu", "Ice Refinement Gu", "Lightning Refinement Gu"], Fx { power: 1.28, ..Fx::NONE }),
    syn!(313, 10, "Forced Extraction Forge", "Refine the living mid-fight.", &["Force Refinement Gu", "Blood Refinement Gu", "Spirit Refinement Gu", "Core Refinement Gu"], Fx { lifesteal: 0.06, power: 1.15, ..Fx::NONE }),
    syn!(314, 10, "Batch Forge Assembly", "Rooms start with throwables.", &["Batch Refinement Gu", "Quick Refinement Gu", "Gentle Refinement Gu", "Success Gu"], Fx { arrows: 1, power: 1.12, ..Fx::NONE }),
    syn!(315, 10, "Supreme Refinement Realm", "Their bullets become lunch.", &["Refine Sea Gu", "Heaven Refinement Gu", "Refine Dao Gu", "Heavenly Essence Treasure Monarch Lotus", "Natural Refinement Gu"], Fx { guard: 0.85, regen: 1.5, power: 1.20, ..Fx::NONE }),
    syn!(316, 10, "Blood-Soul Forge", "Elites become equipment.", &["Blood Refinement Gu", "Spirit Refinement Gu", "Force Refinement Gu", "Core Refinement Gu", "Success Gu"], Fx { power: 1.30, gold: 1.25, ..Fx::NONE }),
    syn!(317, 10, "Gentle Tempering", "Failure stops breaking things.", &["Gentle Refinement Gu", "Nurture Gu"], Fx { guard: 0.94, max_hp: 1.06, ..Fx::NONE }),
    syn!(318, 10, "Quick Forge", "Crafting quickens the hands.", &["Quick Refinement Gu", "Refinement Fire Gu"], Fx { speed: 1.10, power: 1.06, ..Fx::NONE }),
    syn!(319, 10, "Core Shield", "Hammer behind armor.", &["Core Refinement Gu", "Unify Form Gu"], Fx { guard: 0.90, ..Fx::NONE }),
    syn!(320, 10, "Light Forge", "Success flashes blind.", &["Refinement Light Gu", "Refinement Aid Gu", "Refine Gu"], Fx { dodge: 0.06, power: 1.08, ..Fx::NONE }),
    syn!(321, 10, "Elemental Steel", "Plate with a tailwind.", &["Earth Refinement Gu", "Wind Refinement Gu", "Core Refinement Gu"], Fx { guard: 0.90, speed: 1.08, ..Fx::NONE }),
    syn!(322, 10, "Batch Craft", "Breakables drop doubles.", &["Batch Refinement Gu", "Refine Gu", "Quick Refinement Gu"], Fx { gold: 1.25, ..Fx::NONE }),
    syn!(323, 10, "Natural Forge", "Water and rock refuel you.", &["Natural Refinement Gu", "Earth Refinement Gu", "Refinement Water Gu"], Fx { essence_regen: 2.5, ..Fx::NONE }),
    syn!(324, 10, "Blood Craft", "HP spends like essence.", &["Blood Refinement Gu", "Force Refinement Gu", "Refine Gu", "Success Gu"], Fx { power: 1.22, lifesteal: 0.04, ..Fx::NONE }),
    syn!(325, 10, "Soul Refinement Pulse", "Finished crafts stun rooms.", &["Spirit Refinement Gu", "Quiet Refinement Gu", "Gentle Refinement Gu", "Core Refinement Gu"], Fx { power: 1.18, guard: 0.93, ..Fx::NONE }),
    syn!(326, 10, "Refinement Aid", "A fifth off every making.", &["Refinement Aid Gu", "Nurture Gu"], Fx { gold: 1.12, essence_max: 10.0, ..Fx::NONE }),
    syn!(327, 10, "Fire-Water Balance", "Burns trade off with chills.", &["Refinement Fire Gu", "Refinement Water Gu", "Core Refinement Gu"], Fx { power: 1.15, range: 1.08, ..Fx::NONE }),
    syn!(328, 10, "Heavenly Craft", "Chests remember your name.", &["Heaven Refinement Gu", "Refine Dao Gu", "Natural Refinement Gu", "Success Gu"], Fx { gold: 1.30, xp: 1.20, ..Fx::NONE }),
    syn!(329, 10, "Absolute Refinement Realm", "Consumables, doubled, endless.", &["Refine Sea Gu", "Refine Dao Gu", "Success Gu", "Advanced Refinement Gu", "Natural Refinement Gu"], Fx { potion: 1.50, power: 1.22, essence_regen: 2.0, ..Fx::NONE }),
    // ---- Dream Path (11) ----
    syn!(330, 11, "Dream Illusion", "A decoy drinks their volleys.", &["Dream Leaf Gu", "Dream Butterfly Gu"], Fx { guard: 0.93, dodge: 0.03, ..Fx::NONE }),
    syn!(331, 11, "Dream Trap", "Three seconds of elsewhere.", &["Dream Trap Gu", "Dream Realm Gu"], Fx { power: 1.10, ..Fx::NONE }),
    syn!(332, 11, "Sweet Slumber", "Hits become naps.", &["Sweet Dream Gu", "Dream Shield Gu"], Fx { regen: 0.7, guard: 0.94, ..Fx::NONE }),
    syn!(333, 11, "Nightmare Strike", "The stunned dream darker.", &["Nightmare Gu", "Dream Blade Gu"], Fx { power: 1.14, crit: 0.03, ..Fx::NONE }),
    syn!(334, 11, "Dream Travel", "Walls are suggestions.", &["Dream Travel Gu", "Dream Escape Gu"], Fx { dodge: 0.07, speed: 1.06, ..Fx::NONE }),
    syn!(335, 11, "Dreamscape Extraction", "Trap, ward, break for truth.", &["Dream Realm Gu", "Dream Armor Gu", "Unravel Dream Gu"], Fx { power: 1.20, guard: 0.93, ..Fx::NONE }),
    syn!(336, 11, "Sweet Dream Domain", "Half-speed foes, healing you.", &["Sweet Dream Gu", "Dream Domain Gu", "Dream World Gu"], Fx { regen: 1.2, dodge: 0.04, ..Fx::NONE }),
    syn!(337, 11, "Nightmare Terror", "Elites flee, armorless.", &["Nightmare Gu", "Dream Spear Gu", "Dream Control Gu"], Fx { power: 1.16, crit: 0.04, ..Fx::NONE }),
    syn!(338, 11, "Dream Weaver", "Walls for them, doors for you.", &["Dream Tapestry Gu", "Dream Creation Gu", "Dream Form Gu"], Fx { guard: 0.92, power: 1.08, ..Fx::NONE }),
    syn!(339, 11, "Dream Chaser", "Fast wings, clear fog.", &["Dream Chaser Gu", "Dream Wings Gu", "Dream Vision Gu"], Fx { speed: 1.12, range: 1.10, ..Fx::NONE }),
    syn!(340, 11, "Dreamscape Seeker", "Trap, wall, unravel, refresh.", &["Dream Realm Gu", "Dream Armor Gu", "Unravel Dream Gu", "Dream Seeker Gu"], Fx { power: 1.22, essence_regen: 2.0, ..Fx::NONE }),
    syn!(341, 11, "Great Dream Monarch", "Bullets become butterflies.", &["Great Dream Gu", "Dream Wings Gu", "Dream Lord Gu", "Dream World Gu"], Fx { guard: 0.88, lifesteal: 0.04, ..Fx::NONE }),
    syn!(342, 11, "Nightmare Illusion Army", "Your swings, quadrupled in fear.", &["Nightmare Gu", "Dream Form Gu", "Dream Creation Gu", "Dream Illusion Gu"], Fx { power: 1.25, ..Fx::NONE }),
    syn!(343, 11, "Dream Shift Dash", "Infinite blinks, leafy booms.", &["Dream Travel Gu", "Dream Escape Gu", "Dream Wings Gu", "Dream Chaser Gu"], Fx { dodge: 0.10, speed: 1.12, ..Fx::NONE }),
    syn!(344, 11, "Absolute Dream Control", "Elites fight for you briefly.", &["Dream Control Gu", "Dream Soul Gu", "Dream Mind Gu", "Dream Realm Gu"], Fx { power: 1.25, ..Fx::NONE }),
    syn!(345, 11, "Supreme Great Dream Realm", "They sleep; your arts run free.", &["Great Dream Gu", "Dream Wings Gu", "Dream Realm Gu", "Unravel Dream Gu", "Dream Creation Gu"], Fx { power: 1.32, essence_regen: 3.0, ..Fx::NONE }),
    syn!(346, 11, "Nightmare Annihilation", "Sleepers detonate screen-wide.", &["Nightmare Gu", "Dream Blade Gu", "Dream Spear Gu", "Dream Control Gu", "Unravel Dream Gu"], Fx { power: 1.38, crit: 0.06, ..Fx::NONE }),
    syn!(347, 11, "Dream Vision", "Doors can't hide ambushes.", &["Dream Vision Gu", "Dream Sound Gu"], Fx { magnet: 2.0, dodge: 0.03, ..Fx::NONE }),
    syn!(348, 11, "Dream Light", "Accuracy dies in glare.", &["Dream Light Gu", "Dream Form Gu"], Fx { dodge: 0.06, ..Fx::NONE }),
    syn!(349, 11, "Dream Shielding", "Rooms open with armor on.", &["Dream Shield Gu", "Dream Armor Gu"], Fx { guard: 0.90, shieldkill: 3.0, ..Fx::NONE }),
    syn!(350, 11, "Dream Spear Thrust", "Shots ignore shields, add slow.", &["Dream Spear Gu", "Dream Blade Gu", "Dream Light Gu"], Fx { range: 1.20, power: 1.10, ..Fx::NONE }),
    syn!(351, 11, "Nightmare Trap", "Burning dreams, over time.", &["Nightmare Gu", "Dream Trap Gu", "Dream Realm Gu"], Fx { power: 1.15, thorns: 0.10, ..Fx::NONE }),
    syn!(352, 11, "Sweet Slumber Sanctuary", "Lawns of liquid essence.", &["Sweet Dream Gu", "Dream Shield Gu", "Dream Domain Gu"], Fx { essence_regen: 2.5, regen: 0.5, ..Fx::NONE }),
    syn!(353, 11, "Dream Mind Illusion", "Crits sprout spare yous.", &["Dream Mind Gu", "Dream Form Gu", "Dream Illusion Gu"], Fx { dodge: 0.07, guard: 0.94, ..Fx::NONE }),
    syn!(354, 11, "Dream Travel Strike", "Behind you; always crit.", &["Dream Travel Gu", "Dream Blade Gu", "Dream Chaser Gu", "Dream Escape Gu"], Fx { crit: 0.12, power: 1.12, ..Fx::NONE }),
    syn!(355, 11, "Dream Creation Shield", "A dome worth 500.", &["Dream Creation Gu", "Dream World Gu", "Dream Armor Gu", "Dream Shield Gu"], Fx { guard: 0.85, shieldkill: 4.0, ..Fx::NONE }),
    syn!(356, 11, "Dream Sound Sleep", "Lullabies ruin castings.", &["Dream Sound Gu", "Dream Trap Gu"], Fx { guard: 0.94, ..Fx::NONE }),
    syn!(357, 11, "Dream Soul Shift", "Formless, fast, unbothered.", &["Dream Soul Gu", "Dream Form Gu", "Dream Escape Gu"], Fx { speed: 1.12, dodge: 0.05, ..Fx::NONE }),
    syn!(358, 11, "Dream Control Surge", "The room attacks at 60%.", &["Dream Control Gu", "Dream Lord Gu", "Dream World Gu", "Dream Creation Gu"], Fx { guard: 0.90, power: 1.15, ..Fx::NONE }),
    syn!(359, 11, "Absolute Dreamscape Realm", "Death rewinds five seconds.", &["Great Dream Gu", "Dream Lord Gu", "Dream World Gu", "Dream Creation Gu", "Dream Control Gu"], Fx { revive: true, max_hp: 1.15, ..Fx::NONE }),
];
