//! Gu worms of the twelve paths: 360 Gu (30 per path, canon names),
//! ranks 1-6 (mortal..immortal). Table generated by build.rs.
//! Rank maps onto the kept rarity tiers (1 Common … 6 Legendary). Every Gu
//! carries a weapon archetype (how it fights when held) plus 1-3 rule
//! effects. Chests and drafts deal exclusively in Gu now.

use crate::stats::AttrKind;
use crate::weapon_list::{Rarity, WeaponArch};
use ItemEffect as E;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ItemEffect {
    Stat(AttrKind, u32),
    Power(f32),
    Guard(f32),
    Speed(f32),
    Regen(f32),
    Crit(f32),
    Range(f32),
    Homing(f32),
    Arrows(u32),
    Lifesteal(f32),
    Thorns(f32),
    Magnet(f32),
    Dodge(f32),
    Potion(f32),
    Xp(f32),
    ShieldKill(f32),
    Gold(f32),
}

#[derive(Debug, Clone, Copy)]
pub struct GuDef {
    pub name: &'static str,
    pub path: u8,
    pub rank: u8,
    pub arch: WeaponArch,
    pub desc: &'static str,
    pub effects: &'static [ItemEffect],
}

#[derive(Debug, Clone, Copy)]
pub struct GuPath {
    pub name: &'static str,
    pub desc: &'static str,
}

pub const PATHS: [GuPath; 12] = [
    GuPath { name: "Qi Path", desc: "Raw essence, blades of breath. Hit harder, shoot farther." },
    GuPath { name: "Enslavement Path", desc: "Beasts die for you. Shields from the fallen." },
    GuPath { name: "Wisdom Path", desc: "See through everything. Crits, XP, and foresight." },
    GuPath { name: "Transformation Path", desc: "Wear stronger skins. Tanks that run." },
    GuPath { name: "Wood Path", desc: "Root and regrow. Outlast the forest." },
    GuPath { name: "Soul Path", desc: "Drink spirits, refuse death. Sustain forever." },
    GuPath { name: "Luck Path", desc: "Fortune favors you. Crits, gold, narrow escapes." },
    GuPath { name: "Blood Path", desc: "Pay in blood, collect in blood. Lifesteal brawler." },
    GuPath { name: "Food Path", desc: "Eat well, live long. Potions and plenty." },
    GuPath { name: "Theft Path", desc: "Take everything. Gold, lives, Dao itself." },
    GuPath { name: "Refinement Path", desc: "Perfect every vessel. Power through craft." },
    GuPath { name: "Dream Path", desc: "Reality is negotiable. Dodge what never happened." },
];

/// Rank 1 is Common, rank 6 Immortal is Legendary; Epic spans 4-5.
pub fn rank_rarity(rank: u8) -> Rarity {
    match rank {
        1 => Rarity::Common,
        2 => Rarity::Uncommon,
        3 => Rarity::Rare,
        4 | 5 => Rarity::Epic,
        _ => Rarity::Legendary,
    }
}

include!(concat!(env!("OUT_DIR"), "/gu_table.rs"));

/// Chest rarity roll: legends are mythology (2%), commons are lunch (53%).
pub fn roll_item_rarity(seed: u64) -> Rarity {
    match (seed / 31) % 100 {
        98..=99 => Rarity::Legendary,
        93..=97 => Rarity::Epic,
        81..=92 => Rarity::Rare,
        56..=80 => Rarity::Uncommon,
        _ => Rarity::Common,
    }
}

/// Random Gu index of the given rarity (deterministic from seed).
pub fn random_gu_of(rarity: Rarity, seed: u64) -> usize {
    let mut idxs = Vec::new();
    for (i, def) in GU.iter().enumerate() {
        if rank_rarity(def.rank) == rarity {
            idxs.push(i);
        }
    }
    if idxs.is_empty() {
        return 0;
    }
    idxs[(seed as usize) % idxs.len()]
}

/// Random Gu index within a rank band (draft caches deal rank 2-4).
pub fn random_gu_rank(lo: u8, hi: u8, seed: u64) -> usize {
    let mut idxs = Vec::new();
    for (i, def) in GU.iter().enumerate() {
        if def.rank >= lo && def.rank <= hi {
            idxs.push(i);
        }
    }
    if idxs.is_empty() {
        return 0;
    }
    idxs[(seed as usize) % idxs.len()]
}

/// Convert a Gu into an equippable weapon (rank sets base attack).
pub fn gu_weapon(idx: usize, seed: u64) -> Option<crate::weapon_list::Weapon> {
    let def = GU.get(idx)?;
    Some(crate::weapon_list::Weapon {
        name: def.name.to_string(),
        rarity: rank_rarity(def.rank),
        bonus_atk: def.rank as f32 * 2.0 + (seed % 4) as f32,
        arch: def.arch,
    })
}

/// Summed-up inventory power. Multipliers start at 1, adds at 0, best-wins
/// for homing (strongest telepathy rules) and magnet (widest charm wins).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ItemTotals {
    pub power_mult: f32,
    pub guard_mult: f32,
    pub speed_mult: f32,
    pub regen_add: f32,
    pub crit_add: f32,
    pub range_mult: f32,
    pub homing: f32,
    pub arrows_add: u32,
    pub lifesteal: f32,
    pub thorns: f32,
    pub magnet: f32,
    pub dodge_add: f32,
    pub potion_mult: f32,
    pub xp_mult: f32,
    pub shield_kill: f32,
    pub gold_mult: f32,
    /// Max-HP multiplier from set synergies (Ancient Vitality etc).
    pub max_hp_mult: f32,
    /// Flat primeval-essence pool / regen from set synergies.
    pub essence_max_add: f32,
    pub essence_regen_add: f32,
    /// Cheat death once (Bloodline Rebirth etc). Consumed on use.
    pub revive: bool,
}

impl Default for ItemTotals {
    fn default() -> Self {
        Self {
            power_mult: 1.0,
            guard_mult: 1.0,
            speed_mult: 1.0,
            regen_add: 0.0,
            crit_add: 0.0,
            range_mult: 1.0,
            homing: 0.0,
            arrows_add: 0,
            lifesteal: 0.0,
            thorns: 0.0,
            magnet: 0.0,
            dodge_add: 0.0,
            potion_mult: 1.0,
            xp_mult: 1.0,
            shield_kill: 0.0,
            gold_mult: 1.0,
            max_hp_mult: 1.0,
            essence_max_add: 0.0,
            essence_regen_add: 0.0,
            revive: false,
        }
    }
}

/// Same-path resonance: total Gu past the first per path. Each path
/// compliments itself differently (see `apply_resonance`), shown in the
/// saga status via `synergy_summary`.
pub fn resonance(inv: &[usize]) -> [u32; 12] {
    let mut path_n = [0u32; 12];
    for &i in inv {
        if let Some(def) = GU.get(i) {
            if (def.path as usize) < 12 {
                path_n[def.path as usize] += 1;
            }
        }
    }
    path_n
}

/// Unique compliment per path: every extra same-path worm deepens the
/// path's own theme instead of flat damage.
pub fn apply_resonance(t: &mut ItemTotals, inv: &[usize]) {
    let n = resonance(inv);
    let x = |p: usize| n[p].saturating_sub(1) as f32;
    if x(0) > 0.0 {
        t.power_mult *= 1.0 + 0.10 * x(0);
    }
    if x(1) > 0.0 {
        t.shield_kill += 3.0 * x(1);
        t.thorns += 0.10 * x(1);
    }
    if x(2) > 0.0 {
        t.xp_mult *= 1.0 + 0.15 * x(2);
        t.crit_add += 0.02 * x(2);
    }
    if x(3) > 0.0 {
        t.guard_mult *= 0.94f32.powf(x(3));
        t.speed_mult *= 1.0 + 0.03 * x(3);
    }
    if x(4) > 0.0 {
        t.regen_add += 0.5 * x(4);
    }
    if x(5) > 0.0 {
        t.lifesteal += 0.03 * x(5);
    }
    if x(6) > 0.0 {
        t.crit_add += 0.04 * x(6);
        t.gold_mult *= 1.0 + 0.10 * x(6);
    }
    if x(7) > 0.0 {
        t.power_mult *= 1.0 + 0.05 * x(7);
        t.lifesteal += 0.03 * x(7);
    }
    if x(8) > 0.0 {
        t.potion_mult *= 1.0 + 0.20 * x(8);
        t.regen_add += 0.2 * x(8);
    }
    if x(9) > 0.0 {
        t.gold_mult *= 1.0 + 0.15 * x(9);
    }
    if x(10) > 0.0 {
        t.power_mult *= 1.0 + 0.06 * x(10);
    }
    if x(11) > 0.0 {
        t.dodge_add += 0.04 * x(11);
    }
}

/// All Gu indices of a path at an exact rank (milestone boons draft these).
pub fn gu_of_path_rank(path: usize, rank: u8) -> Vec<usize> {
    GU.iter()
        .enumerate()
        .filter(|(_, d)| d.path as usize == path && d.rank == rank)
        .map(|(i, _)| i)
        .collect()
}

/// One-line saga status summary, e.g. "Qi x3 · Blood x2".
pub fn synergy_summary(inv: &[usize]) -> String {
    const SHORT: [&str; 12] = [
        "Qi", "Beast", "Mind", "Skin", "Wood", "Soul",
        "Luck", "Blood", "Food", "Theft", "Craft", "Dream",
    ];
    let n = resonance(inv);
    let mut parts = Vec::new();
    for p in 0..12 {
        if n[p] >= 2 {
            parts.push(format!("{} x{}", SHORT[p], n[p]));
        }
    }
    if parts.is_empty() {
        "none".to_string()
    } else {
        parts.join(" · ")
    }
}

/// Refinement discount from Craft resonance: 10% off per extra worm.
pub fn refine_discount(inv: &[usize]) -> f32 {
    let n = resonance(inv);
    (1.0 - 0.10 * n[10].saturating_sub(1) as f32).max(0.5)
}

impl ItemTotals {
    pub fn of_inventory(inv: &[usize]) -> Self {
        let mut t = Self::default();
        for &i in inv {
            let Some(def) = GU.get(i) else {
                continue;
            };
            for fx in def.effects.iter().copied() {
                match fx {
                    ItemEffect::Stat(_, _) => {}
                    ItemEffect::Power(m) => t.power_mult *= m,
                    ItemEffect::Guard(m) => t.guard_mult *= m,
                    ItemEffect::Speed(m) => t.speed_mult *= m,
                    ItemEffect::Regen(v) => t.regen_add += v,
                    ItemEffect::Crit(v) => t.crit_add += v,
                    ItemEffect::Range(m) => t.range_mult *= m,
                    ItemEffect::Homing(v) => t.homing = t.homing.max(v),
                    ItemEffect::Arrows(n) => t.arrows_add += n,
                    ItemEffect::Lifesteal(v) => t.lifesteal += v,
                    ItemEffect::Thorns(v) => t.thorns += v,
                    ItemEffect::Magnet(v) => t.magnet = t.magnet.max(v),
                    ItemEffect::Dodge(v) => t.dodge_add += v,
                    ItemEffect::Potion(m) => t.potion_mult *= m,
                    ItemEffect::Xp(m) => t.xp_mult *= m,
                    ItemEffect::ShieldKill(v) => t.shield_kill += v,
                    ItemEffect::Gold(m) => t.gold_mult *= m,
                }
            }
        }
        // same-path worms resonate along their path's theme (no flat bonus)
        apply_resonance(&mut t, inv);
        // named set synergies (exact Gu combos, 360 canon)
        crate::synergy::apply_synergies(&mut t, inv);
        t
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn synergy_resonates() {
        // two Qi worms (path 0): one resonance point of raw damage
        let n = resonance(&[0, 1]);
        assert_eq!(n[0], 2);
        // three lone paths: one worm each, no resonance anywhere
        assert_eq!(resonance(&[0, 30, 60]), [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
        // Qi Arrow (Power 1.05) x Qi resonance 1.10
        let t = ItemTotals::of_inventory(&[0, 1]);
        assert!((t.power_mult - 1.05 * 1.10).abs() < 1e-4, "got {}", t.power_mult);
        // summary names the bonded paths
        assert_eq!(synergy_summary(&[0, 1]), "Qi x2");
        assert_eq!(synergy_summary(&[0, 30]), "none");
    }

    #[test]
    fn resonance_themes() {
        // Blood pair drinks and hits: lifesteal + damage, nothing else
        let blood: Vec<usize> = gu_of_path_rank(7, 2);
        assert!(blood.len() >= 2);
        let t = ItemTotals::of_inventory(&blood[..2]);
        assert!(t.lifesteal > 0.0);
        assert!(t.power_mult > 1.0);
        assert_eq!(t.dodge_add, 0.0);
        // Dream worms dodge and never drink; Qi worms only hit —
        // each path compliments itself, never a flat copy
        let dream: Vec<usize> = gu_of_path_rank(11, 2);
        let t = ItemTotals::of_inventory(&dream[..2]);
        assert!(t.dodge_add > 0.0);
        assert_eq!(t.lifesteal, 0.0);
        let t = ItemTotals::of_inventory(&[0, 1]);
        assert_eq!(t.dodge_add, 0.0);
        assert_eq!(t.lifesteal, 0.0);
        assert!(t.power_mult > 1.0);
        // every path can field a boon trio at every milestone rank 2-5
        for p in 0..12usize {
            for r in 2..=5u8 {
                assert!(!gu_of_path_rank(p, r).is_empty(), "path {p} rank {r}");
            }
        }
    }

    #[test]
    fn armory_shape() {
        assert_eq!(GU.len(), 360, "want all 360 Gu");
        assert_eq!(PATHS.len(), 12);
        // thirty Gu per path, ranks span mortal..immortal, names unique
        let mut names = std::collections::HashSet::new();
        for p in 0..12u8 {
            let mine: Vec<&GuDef> = GU.iter().filter(|d| d.path == p).collect();
            assert_eq!(mine.len(), 30, "path {p} must hold 30 Gu");
            assert!(mine.iter().any(|d| d.rank == 1), "path {p} needs rank 1");
            assert!(mine.iter().any(|d| d.rank == 6), "path {p} needs rank 6");
            for d in mine {
                assert!(names.insert(d.name), "duplicate Gu: {}", d.name);
            }
        }
        // every rarity reachable from chests
        for r in [Rarity::Common, Rarity::Uncommon, Rarity::Rare, Rarity::Epic, Rarity::Legendary] {
            let idx = random_gu_of(r, 7);
            assert_eq!(rank_rarity(GU[idx].rank), r);
        }
        // starters: first Gu of each path is rank 1
        for p in 0..12usize {
            assert_eq!(GU[p * 30].path as usize, p);
            assert_eq!(GU[p * 30].rank, 1);
        }
    }
}
